import { createHash } from "crypto";
import { getDataStore } from "./data-store.server";
import { aiService } from "../ai";
import type { TaskType } from "../ai";

import { githubContentsPath } from "./github.server";
import { AI_FIX_EFFORT as AI_FIX_EFFORT, AI_FIX_IDS } from "./fix-meta";
import {
  auditorOutputPath,
  enrichFilesForAuditorFix,
  isAuditorFixId,
} from "./auditor-fixes.server";
import {
  buildDeterministicCiWorkflow,
  sanitizeCiWorkflow,
  shouldUseDeterministicCi,
  assertCiWorkflowStrict,
  finalizeCiWorkflow,
} from "./ci-ai.server";
import { projectUsesTypeScript } from "./project-ci.server";
import { isStaticWebRepo } from "./project-context";
import {
  buildProjectContext,
  projectContextToAiFiles,
  clampNodeVersion,
} from "./project-context.server";
import {
  buildPlaywrightConfig,
  pickPlaywrightConfigPaths,
  playwrightInputFromFiles,
  resolveDevScript,
  resolvePlaywrightTarget,
  resolveWebServerScript,
} from "./playwright-config";
import { stripCodeFence, stripEchoedOutputPath } from "./ai-output-sanitize";
import { validateGeneratedFile } from "./fix-validation";
import { getRepoSnapshot, snapshotFile } from "./repo-snapshot.server";

function hashFiles(files: Record<string, string>, fixIds: string[]): string {
  // Include active provider + model env vars so a model upgrade busts cached outputs
  // generated by the previous model — users get the better quality immediately.
  const modelKey = [
    process.env.AI_PROVIDER ?? "deepseek",
    process.env.DEEPSEEK_MODEL ?? "deepseek-chat",
    process.env.DEEPSEEK_REASONER_MODEL ?? "deepseek-reasoner",
    process.env.CLAUDE_MODEL ?? "claude-sonnet-4-6",
    process.env.CLAUDE_FAST_MODEL ?? "claude-haiku-4-5-20251001",
    process.env.CLAUDE_OPUS_MODEL ?? "claude-opus-4-8",
  ].join(":");
  const stable =
    PROMPT_VERSION +
    modelKey +
    [...fixIds].sort().join(",") +
    JSON.stringify(Object.entries(files).sort());
  return createHash("sha256").update(stable).digest("hex");
}

export { AI_FIX_IDS };

const GITHUB_API = "https://api.github.com";
const README_PATHS = ["README.md", "readme.md", "README", "README.markdown", "Readme.md"];

async function ghFetch(token: string, path: string) {
  return fetch(`${GITHUB_API}${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "LaunchReadyy/1.0",
    },
  });
}

async function fetchFileViaContentsApi(
  token: string,
  fullName: string,
  filePath: string,
): Promise<string | null> {
  const res = await ghFetch(token, `/repos/${fullName}/contents/${githubContentsPath(filePath)}`);
  if (!res.ok) return null;
  const data = (await res.json()) as { content?: string; encoding?: string };
  if (!data.content || data.encoding !== "base64") return null;
  return Buffer.from(data.content.replace(/\n/g, ""), "base64").toString("utf-8");
}

async function fetchFile(
  token: string,
  fullName: string,
  filePath: string,
): Promise<string | null> {
  return snapshotFile(token, fullName, filePath, fetchFileViaContentsApi);
}

async function fetchReadme(token: string, fullName: string): Promise<string | null> {
  for (const path of README_PATHS) {
    const content = await fetchFile(token, fullName, path);
    if (content) return content;
  }
  return null;
}

async function fetchTreePaths(token: string, fullName: string): Promise<string[]> {
  try {
    return (await getRepoSnapshot(token, fullName)).filePaths;
  } catch {
    // Tarball unavailable — fall back to the trees API.
  }
  const repoRes = await ghFetch(token, `/repos/${fullName}`);
  if (!repoRes.ok) return [];
  const repo = (await repoRes.json()) as { default_branch?: string };
  const branch = repo.default_branch ?? "main";
  const res = await ghFetch(token, `/repos/${fullName}/git/trees/${branch}?recursive=1`);
  if (!res.ok) return [];
  const data = (await res.json()) as { tree: Array<{ path: string; type: string }> };
  return data.tree.filter((n) => n.type === "blob").map((n) => n.path);
}

const ENV_SCAN_DIRS = ["src", "app", "pages", "lib", "server", "api"];

async function scanEnvVarUsages(
  token: string,
  fullName: string,
  paths: string[],
): Promise<string[]> {
  const vars = new Set<string>();
  const candidates = paths.filter(
    (p) =>
      /\.(ts|tsx|js|jsx|mjs|cjs)$/.test(p) &&
      ENV_SCAN_DIRS.some((d) => p === `${d}` || p.startsWith(`${d}/`)),
  );
  for (const p of candidates.slice(0, 60)) {
    const content = await fetchFile(token, fullName, p);
    if (!content) continue;
    for (const m of content.matchAll(/process\.env\.([A-Z_][A-Z0-9_]*)/g)) vars.add(m[1]);
    for (const m of content.matchAll(/import\.meta\.env\.([A-Z_][A-Z0-9_]*)/g)) vars.add(m[1]);
  }
  return [...vars].sort();
}

// obj/ and bin/ are .NET build output (generated AssemblyInfo.cs etc. — never app logic worth
// sampling); bin/ elsewhere is launcher stubs (bin/rails, bin/setup), equally not app logic.
// migrations/ is generated schema history (EF Core's Migrations/*.Designer.cs snapshots are
// especially huge) — confirmed against the real davidfowl/TodoApi: 6 of xunit-ai's 12 sample
// slots were EF migration files, crowding out the actual endpoint code the model should ground
// tests in. `<Project>.Tests/` is the .NET test-project naming convention (same repo shipped
// Todo.Api.Tests/, invisible to the `tests/` dir rule).
export const NOT_A_SOURCE_SAMPLE =
  /\.(test|spec)\.|\.d\.ts$|(^|\/)(__tests__|tests|e2e|node_modules|obj|bin|migrations)\/|(^|\/)[^/]+\.tests?\//i;

// Fetches the contents of real source files matching `pattern`, picked from the actual repo
// tree — used to ground test generation in real code instead of a single guessed entry point.
async function fetchSourceSamples(
  token: string,
  fullName: string,
  treePaths: string[],
  pattern: RegExp,
  opts: { max?: number; perFileChars?: number } = {},
): Promise<Record<string, string>> {
  const { max = 12, perFileChars = 5000 } = opts;
  const matches = treePaths
    .filter((p) => pattern.test(p) && !NOT_A_SOURCE_SAMPLE.test(p))
    .slice(0, max);
  const out: Record<string, string> = {};
  for (const p of matches) {
    const c = await fetchFile(token, fullName, p);
    if (c) out[p] = c.slice(0, perFileChars);
  }
  return out;
}

/**
 * Picks the pubspec.yaml governing the sampled Dart sources — the package dir containing the
 * most samples wins. Multi-package repos (confirmed real: roughike/inKino has core/+mobile/+web/
 * packages and no root pubspec.yaml) keep the `package:` import name a test file needs in the
 * pubspec sibling to its lib/, not at the repo root.
 */
export function resolveDartPackagePubspec(
  samplePaths: string[],
  treePaths: string[],
): string | null {
  const counts = new Map<string, number>();
  for (const p of samplePaths) {
    const m = p.match(/^(.*\/)?(?:lib|bin)\//);
    if (!m) continue;
    const prefix = m[1] ?? "";
    counts.set(prefix, (counts.get(prefix) ?? 0) + 1);
  }
  const ranked = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  for (const [prefix] of ranked) {
    const candidate = `${prefix}pubspec.yaml`;
    if (treePaths.includes(candidate)) return candidate;
  }
  return null;
}

// Resolves a TS/JS import specifier to a repo-relative path.
// Returns null for bare package imports (no leading . or @/).
function resolveImportPath(
  fromFile: string,
  specifier: string,
  treePaths: string[],
): string | null {
  let base: string;
  if (specifier.startsWith("./") || specifier.startsWith("../")) {
    const dir = fromFile.includes("/") ? fromFile.replace(/\/[^/]+$/, "") : "";
    base = dir ? `${dir}/${specifier}` : specifier;
  } else if (specifier.startsWith("@/")) {
    base = `src/${specifier.slice(2)}`;
  } else {
    return null; // third-party package — skip
  }
  // Normalise /../ segments
  const parts: string[] = [];
  for (const seg of base.split("/")) {
    if (seg === "..") parts.pop();
    else if (seg && seg !== ".") parts.push(seg);
  }
  const normalised = parts.join("/");
  // Try extensions in order — exact match first, then common extensions, then /index.*
  const tries = [
    normalised,
    `${normalised}.ts`,
    `${normalised}.tsx`,
    `${normalised}.js`,
    `${normalised}.jsx`,
    `${normalised}/index.ts`,
    `${normalised}/index.tsx`,
    `${normalised}/index.js`,
  ];
  for (const t of tries) {
    if (treePaths.includes(t)) return t;
  }
  return null;
}

// Starting from seedPaths, follow import statements up to `depth` hops.
// Returns a map of { filePath: content } for all newly discovered files
// (seeds themselves are NOT included — caller already has them).
async function expandWithImportGraph(
  token: string,
  fullName: string,
  seedPaths: string[],
  treePaths: string[],
  opts: { depth?: number; maxExtra?: number } = {},
): Promise<Record<string, string>> {
  const { depth = 2, maxExtra = 20 } = opts;
  const IMPORT_RE = /(?:^|\n)\s*(?:import|export)[^'"]+['"]([^'"]+)['"]/g;
  const extra: Record<string, string> = {};
  const visited = new Set(seedPaths);
  let frontier = [...seedPaths];

  for (let d = 0; d < depth && Object.keys(extra).length < maxExtra; d++) {
    const nextFrontier: string[] = [];
    for (const filePath of frontier) {
      const content = extra[filePath] ?? (await fetchFile(token, fullName, filePath));
      if (!content) continue;
      let m: RegExpExecArray | null;
      IMPORT_RE.lastIndex = 0;
      while ((m = IMPORT_RE.exec(content)) !== null) {
        const resolved = resolveImportPath(filePath, m[1]!, treePaths);
        if (!resolved || visited.has(resolved)) continue;
        visited.add(resolved);
        nextFrontier.push(resolved);
        if (Object.keys(extra).length >= maxExtra) break;
      }
    }
    // Fetch all next-level files in parallel
    await Promise.all(
      nextFrontier.map(async (p) => {
        if (Object.keys(extra).length >= maxExtra) return;
        const c = await fetchFile(token, fullName, p);
        if (c) extra[p] = c;
      }),
    );
    frontier = nextFrontier;
  }
  return extra;
}

// Last-resort fallback when no real source samples matched (e.g. an unconventional layout) —
// grab whichever known entry point exists so the prompt always has at least one real file.
async function fetchFirstExisting(
  token: string,
  fullName: string,
  candidates: string[],
  perFileChars = 3000,
): Promise<{ path: string; content: string } | null> {
  for (const p of candidates) {
    const c = await fetchFile(token, fullName, p);
    if (c) return { path: p, content: c.slice(0, perFileChars) };
  }
  return null;
}

const FRONTEND_ENTRY_CANDIDATES = [
  "src/App.tsx",
  "src/App.jsx",
  "src/main.tsx",
  "src/main.jsx",
  "app/page.tsx",
  "app/page.jsx",
  "pages/index.tsx",
  "pages/index.jsx",
];
const BACKEND_ENTRY_CANDIDATES = [
  "src/index.ts",
  "src/app.ts",
  "src/server.ts",
  "index.js",
  "app.js",
  "server.js",
];

// Fetch the minimal set of files relevant to each fix type.
async function fetchRelevantFiles(
  token: string,
  fullName: string,
  fixIds: string[],
  framework = "unknown",
): Promise<Record<string, string>> {
  const ctx = await buildProjectContext(token, fullName, framework);
  const files: Record<string, string> = projectContextToAiFiles(ctx);

  const pkg = ctx.pkg.raw ?? files["package.json"] ?? null;

  if (fixIds.includes("readme-ai")) {
    const readme = await fetchReadme(token, fullName);
    // Generous cap — a truncated input here means the model never sees the rest of the README
    // and silently drops it from the output, even though the prompt says to preserve it.
    if (readme) files["README.md"] = readme.slice(0, 16000);

    // Ground the README in verified facts instead of letting the model guess/invent them.
    // Stored under "__"-prefixed keys so buildPrompt can pull them out without rendering them
    // as a fake project file in the generic context block.
    const { badges, scriptsTable, techStack } = extractReadmeFacts(pkg);
    if (badges) files["__badges"] = badges;
    if (scriptsTable) files["__scripts_table"] = scriptsTable;
    if (techStack) files["__tech_stack"] = techStack;

    // Ground "what is this project" in the repo's actual GitHub tagline, and ground "what
    // features does it have" in a real map of route/page/api/component files — instead of
    // letting the model invent a description or claim features that don't exist.
    const repoMetaRes = await ghFetch(token, `/repos/${fullName}`);
    if (repoMetaRes.ok) {
      const repoMeta = (await repoMetaRes.json()) as { description?: string | null };
      if (repoMeta.description) files["__repo_description"] = repoMeta.description;
    }

    const allPaths = ctx.filePaths;
    const structuralPaths = allPaths
      .filter((p) => /\.(ts|tsx|js|jsx|vue|svelte)$/.test(p))
      .filter((p) => /(^|\/)(routes?|pages?|app|api|components|features)(\/|$)/i.test(p))
      .slice(0, 120);
    if (structuralPaths.length > 0) files["__structure"] = structuralPaths.join("\n");

    // Ground "how do I deploy this" in whichever real deploy config files exist — never invent
    // deployment steps for infra we can't verify.
    const deployConfigs = allPaths.filter((p) =>
      /^(vercel\.json|netlify\.toml|fly\.toml|render\.yaml|Procfile|Dockerfile|docker-compose\.ya?ml)$/i.test(
        p,
      ),
    );
    if (deployConfigs.length > 0) files["__deploy_configs"] = deployConfigs.join(", ");
  }

  if (fixIds.includes("ci-ai")) {
    const ci = await fetchFile(token, fullName, ".github/workflows/ci.yml");
    if (ci) files[".github/workflows/ci.yml"] = ci.slice(0, 2000);
    const nvmrc = await fetchFile(token, fullName, ".nvmrc");
    if (nvmrc) files[".nvmrc"] = nvmrc.slice(0, 100);

    const { scripts, dependencies, devDependencies } = parsePackageJson(pkg);
    const allDeps = { ...dependencies, ...devDependencies };
    const allScriptNames = Object.keys(scripts);
    const pkgForCi = {
      scripts,
      dependencies,
      devDependencies,
      nodeVersion: ctx.pkg.nodeVersion,
    };
    if (!("typecheck" in scripts) && projectUsesTypeScript(pkgForCi, ctx.filePaths)) {
      allScriptNames.push("typecheck");
    }
    if (allScriptNames.length > 0) files["__script_names"] = allScriptNames.join(", ");

    // Detect service dependencies so the prompt can add the right service containers.
    // Supabase is a managed cloud service — can't be spun up as a Docker container in CI;
    // flag it separately so the prompt uses env vars instead of a services: block.
    const SERVICE_DEPS: Record<string, string> = {
      pg: "postgres",
      postgres: "postgres",
      mongoose: "mongodb",
      mongodb: "mongodb",
      redis: "redis",
      ioredis: "redis",
      mysql2: "mysql",
      mysql: "mysql",
    };
    const containerServices = [
      ...new Set(
        Object.keys(allDeps)
          .filter((d) => SERVICE_DEPS[d])
          .map((d) => SERVICE_DEPS[d]),
      ),
    ];
    if (containerServices.length > 0) files["__services"] = containerServices.join(", ");
    if (allDeps["@supabase/supabase-js"]) files["__uses_supabase"] = "true";

    // Env vars from .env.example — tells the model which secrets CI jobs actually need.
    const envExample = await fetchFile(token, fullName, ".env.example");
    if (envExample) {
      const envVarNames = envExample
        .split("\n")
        .filter((l) => /^[A-Z_][A-Z0-9_]*=/.test(l.trim()))
        .map((l) => l.trim().split("=")[0])
        .slice(0, 25);
      if (envVarNames.length > 0) files["__env_vars"] = envVarNames.join(", ");
    }

    // Language-specific manifest files — give the AI the actual build/test commands
    // and version constraints for non-Node projects instead of leaving it to guess.
    // Also detect Dockerfile, Playwright config, and deploy configs for extra CI jobs.
    const [
      goMod,
      gemfile,
      pythonRequirements,
      pyprojectToml,
      pipfile,
      cargoToml,
      composerJson,
      pomXml,
      buildGradle,
      rubyVersion,
      pythonVersion,
      toolVersions,
      makefile,
      dockerfile,
      playwrightConfigTs,
      playwrightConfigJs,
      vercelJson,
      flyToml,
      renderYaml,
      railwayJson,
      netlifyToml,
    ] = await Promise.all([
      fetchFile(token, fullName, "go.mod"),
      fetchFile(token, fullName, "Gemfile"),
      fetchFile(token, fullName, "requirements.txt"),
      fetchFile(token, fullName, "pyproject.toml"),
      fetchFile(token, fullName, "Pipfile"),
      fetchFile(token, fullName, "Cargo.toml"),
      fetchFile(token, fullName, "composer.json"),
      fetchFile(token, fullName, "pom.xml"),
      fetchFile(token, fullName, "build.gradle"),
      fetchFile(token, fullName, ".ruby-version"),
      fetchFile(token, fullName, ".python-version"),
      fetchFile(token, fullName, ".tool-versions"),
      fetchFile(token, fullName, "Makefile"),
      fetchFile(token, fullName, "Dockerfile"),
      fetchFile(token, fullName, "playwright.config.ts"),
      fetchFile(token, fullName, "playwright.config.js"),
      fetchFile(token, fullName, "vercel.json"),
      fetchFile(token, fullName, "fly.toml"),
      fetchFile(token, fullName, "render.yaml"),
      fetchFile(token, fullName, "railway.json"),
      fetchFile(token, fullName, "netlify.toml"),
    ]);

    if (goMod) files["go.mod"] = goMod.slice(0, 500);
    if (gemfile) files["Gemfile"] = gemfile.slice(0, 1000);
    if (pythonRequirements) files["requirements.txt"] = pythonRequirements.slice(0, 1000);
    if (pyprojectToml) files["pyproject.toml"] = pyprojectToml.slice(0, 1500);
    if (pipfile) files["Pipfile"] = pipfile.slice(0, 500);
    if (cargoToml) files["Cargo.toml"] = cargoToml.slice(0, 500);
    if (composerJson) files["composer.json"] = composerJson.slice(0, 1000);
    if (pomXml) files["pom.xml"] = pomXml.slice(0, 1500);
    if (buildGradle) files["build.gradle"] = buildGradle.slice(0, 1000);
    if (rubyVersion) files[".ruby-version"] = rubyVersion.trim();
    if (pythonVersion) files[".python-version"] = pythonVersion.trim();
    if (toolVersions) files[".tool-versions"] = toolVersions.trim();
    if (makefile) files["Makefile"] = makefile.slice(0, 1000);

    if (dockerfile) files["__has_dockerfile"] = "true";
    if (playwrightConfigTs || playwrightConfigJs) files["__has_playwright"] = "true";

    const deployPlatform = vercelJson
      ? "Vercel"
      : flyToml
        ? "Fly.io"
        : renderYaml
          ? "Render"
          : railwayJson
            ? "Railway"
            : netlifyToml
              ? "Netlify"
              : null;
    if (deployPlatform) files["__deploy_platform"] = deployPlatform;
  }

  if (fixIds.includes("env-example-ai")) {
    const env = await fetchFile(token, fullName, ".env.example");
    if (env) files[".env.example"] = env.slice(0, 6000);
    const paths = await fetchTreePaths(token, fullName);
    const envVars = await scanEnvVarUsages(token, fullName, paths);
    if (envVars.length) files["detected_env_vars"] = envVars.join(", ");
  }

  if (fixIds.includes("auditor-todo-markers")) {
    // Only match markers inside comment lines — avoids JSX placeholder= attributes
    const TODO_COMMENT_RE =
      /^\s*(?:\/\/|#|\*|\/\*).*\b(TODO|FIXME|HACK|XXX|PLACEHOLDER|not\s+implemented|coming\s+soon)\b/im;
    const treePaths = await fetchTreePaths(token, fullName);
    const candidates = treePaths.filter(
      (p) =>
        /\.(ts|tsx|js|jsx|py|go|rb|php|rs|java|kt|cs|ex|dart|swift)$/.test(p) &&
        !/(test|spec|\.d\.ts$|node_modules|__tests__|\.git)/.test(p),
    );
    const todoFiles: string[] = [];
    for (const p of candidates) {
      if (todoFiles.length >= 8) break;
      const content = await fetchFile(token, fullName, p);
      if (content && TODO_COMMENT_RE.test(content)) {
        files[p] = content;
        files[`__todo_lines_${p}`] = String(content.split("\n").length);
        todoFiles.push(p);
      }
    }
    if (todoFiles.length > 0) {
      files["__todo_files"] = JSON.stringify(todoFiles);
      // Expand with import graph — AI sees full type/import context for each TODO file
      const importCtx = await expandWithImportGraph(token, fullName, todoFiles, treePaths, {
        depth: 2,
        maxExtra: 20,
      });
      for (const [p, c] of Object.entries(importCtx)) {
        if (!files[p]) files[p] = c; // don't overwrite todo files themselves
      }
    }
  }

  // Test fixes get several real source files now, not just one guessed entry point — grounds
  // the generated tests in actual components/pages/routes instead of one file's worth of code.
  const needsSourceSamples =
    fixIds.includes("vitest-ai") ||
    fixIds.includes("playwright-ai") ||
    fixIds.includes("api-tests") ||
    fixIds.includes("pytest-ai") ||
    fixIds.includes("go-test-ai") ||
    fixIds.includes("rspec-ai") ||
    fixIds.includes("phpunit-ai") ||
    fixIds.includes("junit-ai") ||
    fixIds.includes("cargo-test-ai") ||
    fixIds.includes("xunit-ai") ||
    fixIds.includes("exunit-ai") ||
    fixIds.includes("dart-test-ai") ||
    fixIds.includes("swift-test-ai") ||
    fixIds.includes("kotlin-test-ai");
  const auditorFixIdsPresent = fixIds.some(isAuditorFixId);
  const sourceTreePaths =
    needsSourceSamples || auditorFixIdsPresent ? await fetchTreePaths(token, fullName) : [];

  if (fixIds.includes("vitest-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(components|hooks|lib|utils)\/.*\.(tsx?|jsx?)$/i,
    );
    if (Object.keys(samples).length > 0) {
      Object.assign(files, samples);
    } else {
      const fallback = await fetchFirstExisting(token, fullName, FRONTEND_ENTRY_CANDIDATES);
      if (fallback) files[fallback.path] = fallback.content;
    }
  }

  if (fixIds.includes("playwright-ai")) {
    const configPaths = pickPlaywrightConfigPaths(ctx.filePaths);
    await Promise.all(
      configPaths.map(async (p) => {
        const content = await fetchFile(token, fullName, p);
        if (content) files[p] = content.slice(0, 4000);
      }),
    );
    const envExample = await fetchFile(token, fullName, ".env.example");
    if (envExample) files[".env.example"] = envExample.slice(0, 2000);

    const lang = ctx.language;
    const routePattern =
      lang === "python"
        ? /(^|\/)(templates?|views?|pages?|routes?)\/.*\.(py|html)$|\.html$/i
        : lang === "ruby"
          ? /(^|\/)app\/views\/.*\.(erb|haml|slim)$|(^|\/)config\/routes\.rb$/i
          : lang === "php"
            ? /(^|\/)resources\/views\/.*\.(php|blade\.php)$|(^|\/)routes\/web\.php$/i
            : lang === "java" || lang === "kotlin"
              ? /(^|\/)(templates?|resources\/templates)\/.*\.(html|ftl)$|(^|\/)(controllers?)\/.*\.(java|kt)$/i
              : lang === "go"
                ? /(^|\/)(templates?|static|public)\/.*\.(html|tmpl|go)$|(^|\/)(handlers?|routes?)\/.*\.go$/i
                : /(^|\/)(pages|app|routes|templates?|views?)\/(?!api\/).*\.(tsx?|jsx?|vue|svelte|html)$/i;

    const samples = await fetchSourceSamples(token, fullName, sourceTreePaths, routePattern);
    if (Object.keys(samples).length > 0) {
      Object.assign(files, samples);
    } else {
      const fallback = await fetchFirstExisting(token, fullName, FRONTEND_ENTRY_CANDIDATES);
      if (fallback) files[fallback.path] = fallback.content;
    }
  }

  if (fixIds.includes("api-tests")) {
    const lang = files["__language"] ?? "node";
    const apiPattern =
      lang === "python"
        ? /(^|\/)(routes?|views?|api|app)\/.*\.py$/i
        : lang === "go"
          ? /(^|\/)(internal|pkg|api|handlers?)\/.*\.go$/i
          : lang === "ruby"
            ? /(^|\/)(app\/controllers|api)\/.*\.rb$/i
            : lang === "php"
              ? /(^|\/)(routes|app\/Http|api)\/.*\.php$/i
              : lang === "java" || lang === "kotlin"
                ? /(^|\/)(controllers?|api|rest)\/.*\.(java|kt)$/i
                : lang === "rust"
                  ? /(^|\/)(src\/routes|src\/handlers|api)\/.*\.rs$/i
                  : lang === "dart"
                    ? /(^|\/)(lib|api)\/.*\.dart$/i
                    : lang === "swift"
                      ? /(^|\/)(Sources|App|api)\/.*\.swift$/i
                      : /(^|\/)(routes|controllers|api)\/.*\.(tsx?|jsx?)$/i;
    const samples = await fetchSourceSamples(token, fullName, sourceTreePaths, apiPattern);
    if (Object.keys(samples).length > 0) {
      Object.assign(files, samples);
    } else {
      const fallback = await fetchFirstExisting(token, fullName, BACKEND_ENTRY_CANDIDATES);
      if (fallback) files[fallback.path] = fallback.content;
    }
  }

  if (fixIds.includes("pytest-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(src|app|lib|api|routes?)\/.*\.py$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("go-test-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(internal|pkg|cmd|api|handlers?)\/.*\.go$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
    // Without go.mod the model can only invent the module path for imports (usually from the
    // repo URL) — confirmed against a real repo + real generation: a guessed path fails
    // `go test` outright with "no required module provides package", while the identical test
    // logic passes once the real module path is used. Vanity import paths, /v2 suffixes, and
    // forks all break URL-based guessing; the declared path never does.
    const goMod = await fetchFile(token, fullName, "go.mod");
    if (goMod) files["go.mod"] = goMod.slice(0, 2000);
  }

  if (fixIds.includes("rspec-ai")) {
    // Root-level .rb files matter: Sinatra apps conventionally keep app.rb at the repo root
    // (confirmed against the real bbc/REST-API-example — the app//lib/-only pattern matched
    // ZERO files there, leaving the model to hallucinate tests for code it never saw, the same
    // bug class as xunit-ai's src/-anchored pattern).
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(app|lib)\/.*\.rb$|^[^/]+\.rb$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("phpunit-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(app|src|routes)\/.*\.php$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("junit-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(src\/main\/java|src\/test\/java)\/.*\.java$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("cargo-test-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(src|crates)\/.*\.rs$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("xunit-ai")) {
    // C# repos conventionally keep code under `<ProjectName>/`, not `src/` — confirmed against
    // a real repo (FabianGosebrink/ASPNETCore-WebAPI-Sample) that a src/-anchored pattern
    // matched zero files, leaving the model to hallucinate tests for classes it never saw.
    // Any .cs file qualifies; NOT_A_SOURCE_SAMPLE already excludes obj//bin/ build output.
    const samples = await fetchSourceSamples(token, fullName, sourceTreePaths, /\.cs$/i);
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("exunit-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(lib|test)\/.*\.exs?$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("dart-test-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(lib|bin)\/.*\.dart$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
    // Multi-package repos have no root pubspec.yaml (confirmed real: roughike/inKino is
    // core/+mobile/+web/, each its own package) — the `package:` import name lives in the
    // pubspec sibling to the sampled lib/, so resolve it from wherever the samples came from.
    if (!files["pubspec.yaml"]) {
      const pubspecPath = resolveDartPackagePubspec(Object.keys(samples), sourceTreePaths);
      if (pubspecPath) {
        const c = await fetchFile(token, fullName, pubspecPath);
        if (c) files["pubspec.yaml"] = c.slice(0, 1500);
      }
    }
  }

  if (fixIds.includes("swift-test-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(Sources|App|ios|macos)\/.*\.swift$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  if (fixIds.includes("kotlin-test-ai")) {
    const samples = await fetchSourceSamples(
      token,
      fullName,
      sourceTreePaths,
      /(^|\/)(src\/main|app\/src\/main)\/.*\.(kt|kts)$/i,
    );
    if (Object.keys(samples).length > 0) Object.assign(files, samples);
  }

  const auditorFixIds = fixIds.filter(isAuditorFixId);
  if (auditorFixIds.length > 0) {
    const fetchOne = (path: string) => fetchFile(token, fullName, path);
    for (const fixId of auditorFixIds) {
      await enrichFilesForAuditorFix(fixId, ctx, files, fetchOne);

      // The target file alone isn't enough context — a route can call into a service/helper
      // that already does the verification/validation/auth this fix is meant to add, and the
      // model can't check for that (even with an explicit prompt instruction to) if that file
      // was never fetched. Pull in what the target file imports so the model can actually see it.
      const target = files["__auditor_target"];
      if (target && /\.(ts|tsx|js|jsx|mjs|cjs)$/.test(target) && sourceTreePaths.length > 0) {
        const importCtx = await expandWithImportGraph(token, fullName, [target], sourceTreePaths, {
          depth: 2,
          maxExtra: 10,
        });
        for (const [p, c] of Object.entries(importCtx)) {
          if (!files[p]) files[p] = c;
        }
      }
    }
  }

  // For any fix that fetched source samples, expand with the import graph so AI sees
  // the full connected context — types, utilities, parent components — not just the sampled files.
  if (needsSourceSamples && sourceTreePaths.length > 0) {
    const seedPaths = Object.keys(files).filter(
      (p) => !p.startsWith("__") && /\.(ts|tsx|js|jsx)$/.test(p),
    );
    if (seedPaths.length > 0) {
      const importCtx = await expandWithImportGraph(token, fullName, seedPaths, sourceTreePaths, {
        depth: 2,
        maxExtra: 25,
      });
      for (const [p, c] of Object.entries(importCtx)) {
        if (!files[p]) files[p] = c;
      }
    }
  }

  return files;
}

// Parses scripts/license/node-engine straight from the FULL package.json — never the 3000-char
// slice used for general context, which can clip the scripts block out entirely on larger
// projects. Anything that needs ground truth (not a guess) about the manifest goes through this.
function parsePackageJson(pkgJson: string | null | undefined): {
  scripts: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  license?: string;
  nodeEngine?: string;
} {
  try {
    const pkg = JSON.parse(pkgJson ?? "{}") as {
      scripts?: Record<string, string>;
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
      license?: string;
      engines?: { node?: string };
    };
    return {
      scripts: pkg.scripts ?? {},
      dependencies: pkg.dependencies ?? {},
      devDependencies: pkg.devDependencies ?? {},
      license: pkg.license,
      nodeEngine: pkg.engines?.node,
    };
  } catch {
    return { scripts: {}, dependencies: {}, devDependencies: {} };
  }
}

// Groups raw package.json deps into human-readable buckets for the README Tech Stack section.
// The key rule: if a package family has 4+ members (e.g. @radix-ui/*), collapse them into one
// summary line — nobody reading a README wants a 30-item list of Radix primitives.
function buildTechStackSummary(
  deps: Record<string, string>,
  devDeps: Record<string, string>,
): string {
  type Bucket = { label: string; items: string[] };
  const framework: Bucket = { label: "Framework & Runtime", items: [] };
  const routing: Bucket = { label: "Routing & State", items: [] };
  const ui: Bucket = { label: "UI & Components", items: [] };
  const viz: Bucket = { label: "Visualization", items: [] };
  const styling: Bucket = { label: "Styling", items: [] };
  const forms: Bucket = { label: "Forms & Validation", items: [] };
  const utilities: Bucket = { label: "Utilities", items: [] };
  const tooling: Bucket = { label: "Tooling", items: [] };

  const FRAMEWORK = new Set([
    "react",
    "react-dom",
    "next",
    "vite",
    "express",
    "fastify",
    "hono",
    "remix",
    "gatsby",
    "astro",
    "vue",
    "svelte",
  ]);
  const VIZ = new Set([
    "reactflow",
    "d3",
    "d3-force",
    "d3-hierarchy",
    "cytoscape",
    "vis-network",
    "sigma",
    "echarts",
    "recharts",
    "chart.js",
    "victory",
  ]);
  const STYLING = new Set([
    "tailwindcss",
    "tailwind-merge",
    "tw-animate-css",
    "clsx",
    "class-variance-authority",
    "styled-components",
    "@emotion/react",
    "@emotion/styled",
  ]);
  const FORMS = new Set(["react-hook-form", "formik", "zod", "yup", "joi", "valibot"]);
  const NOTABLE_UI = new Set([
    "framer-motion",
    "motion",
    "sonner",
    "vaul",
    "cmdk",
    "lucide-react",
    "react-icons",
    "react-resizable-panels",
    "embla-carousel-react",
    "react-day-picker",
    "input-otp",
  ]);
  const TOOLING_DEV = new Set([
    "typescript",
    "vitest",
    "@vitest/coverage-v8",
    "@vitest/coverage-istanbul",
    "jest",
    "@jest/globals",
    "eslint",
    "prettier",
    "@playwright/test",
    "playwright",
  ]);

  const radixNames: string[] = [];

  for (const [name, version] of Object.entries(deps)) {
    if (FRAMEWORK.has(name)) {
      framework.items.push(`**${name}** \`${version}\``);
    } else if (name.startsWith("@tanstack/")) {
      const short = name.replace("@tanstack/react-", "").replace("@tanstack/", "");
      routing.items.push(`**TanStack ${short}** \`${version}\``);
    } else if (name.startsWith("@radix-ui/")) {
      radixNames.push(name.replace("@radix-ui/react-", ""));
    } else if (VIZ.has(name)) {
      viz.items.push(`**${name}** \`${version}\``);
    } else if (name.startsWith("@tailwindcss/") || STYLING.has(name)) {
      styling.items.push(`**${name}**`);
    } else if (name.startsWith("@hookform/") || FORMS.has(name)) {
      forms.items.push(`**${name}**`);
    } else if (NOTABLE_UI.has(name)) {
      ui.items.push(`**${name}** \`${version}\``);
    } else if (
      name.startsWith("@vercel/") ||
      name.startsWith("@sentry/") ||
      name.startsWith("@stripe/") ||
      name.startsWith("@auth/") ||
      name.startsWith("@supabase/") ||
      name.startsWith("@clerk/") ||
      name.startsWith("date-fns") ||
      name === "uuid" ||
      name === "nanoid" ||
      name === "axios" ||
      name === "ky" ||
      name === "zustand" ||
      name === "jotai" ||
      name === "recoil"
    ) {
      utilities.items.push(`**${name}** \`${version}\``);
    } else {
      utilities.items.push(`**${name}** \`${version}\``);
    }
  }

  // Collapse large Radix families into a single readable line
  if (radixNames.length >= 4) {
    const preview = radixNames.slice(0, 5).join(", ");
    const suffix = radixNames.length > 5 ? `, … (+${radixNames.length - 5} more)` : "";
    ui.items.unshift(
      `**Radix UI** — ${radixNames.length} accessible primitives (${preview}${suffix})`,
    );
  } else {
    for (const n of radixNames) ui.items.unshift(`**@radix-ui/react-${n}**`);
  }

  // Pull notable devDeps (TypeScript, test runners, linters) into Tooling bucket
  // Also grab tailwindcss from devDeps if it wasn't in deps (common with TW v4)
  if (devDeps["tailwindcss"] && !deps["tailwindcss"]) {
    styling.items.push(`**tailwindcss** \`${devDeps["tailwindcss"]}\``);
  }
  for (const [name, version] of Object.entries(devDeps)) {
    if (TOOLING_DEV.has(name)) {
      tooling.items.push(`**${name}** \`${version}\``);
    }
  }

  return [framework, routing, ui, viz, styling, forms, utilities, tooling]
    .filter((b) => b.items.length > 0)
    .map((b) => `### ${b.label}\n${b.items.map((i) => `- ${i}`).join("\n")}`)
    .join("\n\n");
}

// Pulls README-worthy facts directly out of package.json — license badge, the exact npm scripts
// table, and a grouped tech stack summary — instead of letting the model guess or invent
// script/library names. The AI only writes the human prose around these verified facts.
export function extractReadmeFacts(pkgJson: string | null | undefined): {
  badges: string;
  scriptsTable: string;
  techStack: string;
} {
  const { scripts, dependencies, devDependencies, license, nodeEngine } = parsePackageJson(pkgJson);

  const badgeParts: string[] = [];
  if (license) {
    badgeParts.push(
      `![License](https://img.shields.io/badge/license-${encodeURIComponent(license)}-blue)`,
    );
  }
  if (nodeEngine) {
    badgeParts.push(
      `![Node](https://img.shields.io/badge/node-${encodeURIComponent(nodeEngine)}-brightgreen)`,
    );
  }

  const scriptEntries = Object.entries(scripts);
  const scriptsTable =
    scriptEntries.length > 0
      ? [
          "| Command | Runs |",
          "| --- | --- |",
          ...scriptEntries.map(([name, cmd]) => `| \`npm run ${name}\` | \`${cmd}\` |`),
        ].join("\n")
      : "";

  // Group deps into readable buckets — collapses large families (e.g. Radix UI) into one line.
  const techStack = buildTechStackSummary(dependencies, devDependencies);

  return { badges: badgeParts.join(" "), scriptsTable, techStack };
}

export function buildPrompt(
  fixId: string,
  files: Record<string, string>,
  repoUrl?: string,
  framework?: string,
  feedback?: string,
  repoKnowledge?: string,
): string {
  const fw =
    files["__framework"] && files["__framework"] !== "unknown"
      ? files["__framework"]
      : framework && framework !== "unknown"
        ? framework
        : "JavaScript";
  const isReact = fw !== "Express";
  // "__"-prefixed keys are deterministic facts for a specific prompt branch (e.g. readme-ai's
  // badges/scripts table) — render them separately, not as a fake project file.
  const contextFiles = Object.entries(files).filter(([p]) => !p.startsWith("__"));
  const knowledgeBlock = repoKnowledge?.trim()
    ? `\n\nRepository knowledge (from prior scans — prefer these facts over guesses):\n${repoKnowledge.trim()}\n`
    : "";
  const ctx =
    knowledgeBlock +
    (contextFiles.length > 0
      ? "\n\nProject files for context:\n\n" +
        contextFiles.map(([p, c]) => `<file path="${p}">\n${c}\n</file>`).join("\n\n")
      : "") +
    (feedback
      ? `\n\nThe user reviewed a previous attempt and asked for changes: "${feedback}"\nApply this feedback while still following all requirements above.`
      : "");

  const repoNote = repoUrl ? `Repo: ${repoUrl}` : "";

  if (fixId === "ci-ai") {
    const nvmrc = files[".nvmrc"]?.trim().replace(/^v/, "").match(/\d+/)?.[0];
    const enginesNode =
      files["__node_engine"]?.match(/\d+/)?.[0] ??
      (() => {
        try {
          const pkg = JSON.parse(files["package.json"] ?? "{}") as { engines?: { node?: string } };
          return pkg.engines?.node?.match(/\d+/)?.[0];
        } catch {
          return undefined;
        }
      })();
    const nodeVersion = clampNodeVersion(nvmrc ?? enginesNode);
    const scriptNames = files["__script_names"] ?? "";
    const scripts = new Set(
      scriptNames
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    );
    const packageManager = files["__package_manager"] ?? "npm";
    const installCmd =
      packageManager === "pnpm"
        ? "pnpm install"
        : packageManager === "yarn"
          ? "yarn install"
          : "npm install";
    const runCmd =
      packageManager === "pnpm" ? "pnpm run" : packageManager === "yarn" ? "yarn run" : "npm run";
    const auditCmd =
      packageManager === "pnpm"
        ? "pnpm audit --audit-level high"
        : packageManager === "yarn"
          ? "yarn npm audit --severity high"
          : "npm audit --audit-level=high";
    const hasCoverage = files["__has_coverage"];
    const services = files["__services"];
    const usesSupabase = files["__uses_supabase"];
    const envVars = files["__env_vars"];
    const hasDockerfile = files["__has_dockerfile"];
    const hasPlaywright = files["__has_playwright"];
    const deployPlatform = files["__deploy_platform"];
    const isNodeProject = !!files["package.json"];
    const isNonJsLang =
      fw !== "JavaScript" &&
      fw !== "Next.js" &&
      fw !== "Vite" &&
      fw !== "React" &&
      fw !== "Express";
    // This branch of ci-ai only runs for repos the deterministic generator can't handle
    // (unknown language, no package.json) — the most common real shape of which is a plain
    // static HTML site. Without explicit instructions for that case, a real generation produced
    // three placeholder jobs that only echoed "No X script defined. Skipping." — decorative
    // always-green CI that checks nothing.
    const ciFilePaths = files["__file_paths"]?.split("\n").filter(Boolean) ?? [];
    const isStaticSite = !isNodeProject && isStaticWebRepo(ciFilePaths);

    const setupBlock = isNodeProject
      ? `      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: '${packageManager}'
      - run: ${installCmd}`
      : "";

    return `You are a senior DevOps engineer writing a production-grade GitHub Actions CI workflow for a ${fw} project.${repoUrl ? " " + repoNote : ""}

CRITICAL RULE — MULTI-JOB PARALLEL STRUCTURE:
Do NOT write a single flat job. Write MULTIPLE jobs that run in parallel where possible.
Jobs that have no dependency on each other MUST run concurrently — do not add unnecessary \`needs:\`.

Required jobs and their dependencies:

${
  isNodeProject
    ? `JOB: "quality" (runs on ubuntu-latest, NO needs)
  Purpose: fast feedback on code correctness before expensive steps
  Steps:
    - actions/checkout@v4
    ${setupBlock}
${scripts.has("lint") ? `    - run: ${runCmd} lint` : ""}
${scripts.has("typecheck") ? `    - run: ${runCmd} typecheck` : ""}
  ${!scripts.has("lint") && !scripts.has("typecheck") ? "Skip this job entirely if neither lint nor typecheck exists in the script list." : ""}

JOB: "test" (runs on ubuntu-latest, NO needs — runs in parallel with quality)${
        services
          ? `\n  services: Add Docker service containers for: ${services}
    Use standard images (postgres:16, redis:7, mongo:7, mysql:8) with health checks on standard ports (5432, 6379, 27017, 3306)`
          : ""
      }${
        usesSupabase
          ? `\n  Supabase cannot run as a Docker container — reference SUPABASE_URL and SUPABASE_ANON_KEY as \${{ secrets.VAR_NAME }}`
          : ""
      }${
        envVars
          ? `\n  env block: Reference these .env.example vars as \${{ secrets.VAR_NAME }}: ${envVars}
    Only include vars that the test command actually needs — skip runtime-only vars (webhooks, OAuth redirect URLs)`
          : ""
      }
  Steps:
    - actions/checkout@v4
    ${setupBlock}
${scripts.has("test") ? `    - run: ${runCmd} test${hasCoverage ? " -- --coverage" : ""}` : "    (no test script detected — omit this job)"}
${
  hasCoverage && scripts.has("test")
    ? `    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/`
    : ""
}

JOB: "build" (runs on ubuntu-latest, needs: [quality])
  Steps:
    - actions/checkout@v4
    ${setupBlock}
${scripts.has("build") ? `    - run: ${runCmd} build` : "    (no build script — omit this job)"}
${
  hasDockerfile
    ? `
JOB: "docker" (runs on ubuntu-latest, needs: [build])
  Purpose: verify the Docker image builds successfully — no push, just build validation
  Steps:
    - actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - run: docker build . --tag app:ci --cache-from type=gha --cache-to type=gha,mode=max`
    : ""
}
${
  hasPlaywright
    ? `
JOB: "e2e" (runs on ubuntu-latest, needs: [build])
  Purpose: end-to-end browser tests against the built app
  Steps:
    - actions/checkout@v4
    ${setupBlock}
    - run: ${runCmd === "npm run" ? "npx" : runCmd} playwright install --with-deps
    - run: ${runCmd} test:e2e (or the actual e2e script name from the list, or \`npx playwright test\` if no script exists)`
    : ""
}
${
  deployPlatform
    ? `
JOB: "deploy" (runs on ubuntu-latest, needs: [build${scripts.has("test") ? ", test" : ""}])
  Condition: if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  Purpose: deploy to ${deployPlatform} only on successful merge to main, never on PRs
  Steps: Use the official ${deployPlatform} GitHub Action or CLI — reference deploy token as \${{ secrets.${deployPlatform.toUpperCase().replace(/[^A-Z]/g, "_")}_TOKEN }}`
    : ""
}

JOB: "security" (runs on ubuntu-latest, NO needs — runs in parallel with everything)
  Purpose: fail the workflow on high-severity dependency vulnerabilities
  Steps:
    - actions/checkout@v4
    ${setupBlock}
    - run: ${auditCmd}
  Do NOT add continue-on-error — audit failures must block merge.`
    : isStaticSite
      ? `
Static website (HTML/CSS, no build system, no package manager) — write a single "validate" job:
  Steps:
    - actions/checkout@v4
    - uses: actions/setup-node@v4 with node-version: '20' (only to provide npx for the validator)
    - run: npx --yes html-validate "**/*.html"
  Do NOT invent lint/typecheck/test/build jobs for scripts and tooling that do not exist in this repo.`
      : `
Non-Node language (${fw}) — write a single "ci" job (or split into quality + test if the language supports it):
  - Use the correct language setup action pinned to the version in the manifest files below
  - Use the correct package manager and install command for ${fw}
  - Run ONLY the checks that actually exist in the Makefile/manifest shown below (build, lint,
    typecheck, test). If a target does not exist (e.g. the Makefile has no test target), OMIT
    that step entirely — never write an echo placeholder step for it, and never add YAML
    comments discussing the omission.
  - Do NOT add actions/setup-node or npm steps
  ${isNonJsLang ? `Language-specific details: infer install and test commands from the project files shown in context` : ""}`
}

Global requirements (apply to ALL jobs):
- Top-level triggers: push to branches [main, master, develop] AND pull_request (no branch filter on PRs)
- NEVER use continue-on-error on lint, typecheck, test, build, or audit steps — failed gates must fail the workflow
- NEVER write a placeholder job whose steps only echo a message — every job must run a real check; if a check has nothing to run in this repo, omit that job entirely
- Top-level concurrency block (cancel superseded runs on same branch):
  concurrency:
    group: \${{ github.workflow }}-\${{ github.ref }}
    cancel-in-progress: true
- Use actions/checkout@v4 everywhere
- IMPORTANT: GitHub Actions expressions (\${{ }}) do NOT support JavaScript syntax — no optional chaining (?.), no nullish coalescing (??), no fromJson calls${ctx}

Return ONLY the complete YAML file content. No markdown fences, no explanation.
Output path: .github/workflows/ci.yml`;
  }

  if (fixId === "readme-ai") {
    const badges = files["__badges"];
    const scriptsTable = files["__scripts_table"];
    const techStack = files["__tech_stack"];
    const repoDescription = files["__repo_description"];
    const structure = files["__structure"];
    const deployConfigs = files["__deploy_configs"];
    const detectedEnvVars = files["detected_env_vars"];
    return `You are a technical writer creating a production-quality README for a ${fw} project.${repoUrl ? " " + repoNote : ""}

A real README leads with what the project IS before how to run it. Write or improve the README
with these sections, in this order:

1. "## Overview" — 2-4 sentences on what this project does and who it's for.${
      repoDescription
        ? ` The repo's own description is: "${repoDescription}" — treat this as ground truth, do not contradict it.`
        : ` No repo description is available — infer the purpose ONLY from the file structure and existing README content below. If you genuinely can't tell, write one honest sentence about what kind of project it is (e.g. "a TypeScript API service") rather than inventing details.`
    }
2. "## Features" — a bullet list of real, specific capabilities. Every bullet must be evidenced by
   something in the detected source files or existing README below (a routes/pages file implies
   that page or endpoint exists). Do NOT invent features that aren't backed by the project's
   actual files.${structure ? `\n\nDetected source files (routes/pages/api/components):\n${structure}` : ""}

Then continue with the setup section:
- Use the actual repo name and detected framework
- List prerequisites, install command, dev command, test command from package.json scripts
- Include env var setup if .env.example is relevant.${
      detectedEnvVars
        ? ` These real env vars were detected in the codebase: ${detectedEnvVars}. Only mention these — do NOT invent additional variable names.`
        : ` No env vars were detected in the codebase — do NOT invent specific variable names (no guessed HOST/DATABASE_URL/etc.); write one generic sentence pointing to .env.example instead.`
    }
- Add a "## Deployment" section.${
      deployConfigs
        ? ` This repo has real deploy config files detected: ${deployConfigs}. Base the deployment
  instructions on EXACTLY these files — do not invent steps for platforms that aren't evidenced here.`
        : ` No deploy config files were detected — write ONE honest sentence saying deployment depends
  on the hosting provider chosen, and link to the official deploy docs for ${fw} if one is well-known.
  Do NOT invent specific deployment steps, platforms, or commands you can't verify exist in this repo.`
    }
- Add a brief "## Contributing" section with the standard fork → branch → PR flow and a reminder
  to run the test/lint scripts from the Scripts table before opening a PR. This is generic,
  process-only advice — fine to write without repo-specific evidence.
- If a README is shown below, you MUST preserve every existing section, screenshot, prose
  paragraph, and table byte-for-byte — only ADD the sections above and a "## Getting Started"
  section covering prerequisites/install/env/dev commands. Do not shorten, summarize, reorder, or
  remove any existing prose/screenshot/table content for any reason, including length.
  EXCEPTION, so the result has no duplicate sections: if the existing README already has one or
  more short sections whose ENTIRE content is just a heading plus a single fenced command (e.g.
  "## Setup" / "## Lint" / "## Test" / "## Development" each containing only one shell command,
  with no other prose), and that exact command is now covered by your new "## Getting
  Started"/"## Scripts" sections, DELETE those old redundant single-command sections — do not
  keep the same command under two different headings. This exception applies ONLY to
  single-command sections being folded into Getting Started/Scripts; every other existing section
  (anything with real prose, a screenshot, or content not reproduced elsewhere) is still untouchable.${
    badges
      ? `\n- Place this exact badges line right under the title — copy it verbatim, do not invent or remove badges: ${badges}`
      : ""
  }${
    scriptsTable
      ? `\n- Include a "## Scripts" section. Use this exact table — do not invent rows or change any command, but you may add a one-sentence "Description" column explaining what each one does:\n${scriptsTable}`
      : ""
  }${ctx}

Return ONLY the full README.md markdown content. No markdown fences, no explanation.
Output path: README.md`;
  }

  if (fixId === "env-example-ai") {
    const vars = files["detected_env_vars"] ?? "";
    const hasExisting = !!files[".env.example"];
    return `You are a developer documenting environment variables for a ${fw} project.${repoUrl ? " " + repoNote : ""}

${hasExisting ? `An existing .env.example is shown below in the project files. Your job is to EXTEND it — preserve every existing line exactly, then append any variables from the detected list that are not already present. Do NOT rewrite or reorder the existing content.` : `Write a .env.example file:`}
- Include every env var found in the codebase${vars ? ` (${vars})` : ""}${
      vars
        ? ""
        : `\n- No specific env vars were detected in this codebase. Do NOT invent variables for features (auth, database, redis, rate limiting, third-party APIs) that aren't evidenced by the project files below — write only the safe, near-universal basics for a ${fw} service (e.g. NODE_ENV, PORT) rather than guessing at ones that may not exist.`
    }
- Add a short comment above each new variable explaining what it is
- Use placeholder values (your-api-key-here, postgres://localhost:5432/db) — never real secrets${ctx}

Return ONLY the complete .env.example file content. No markdown fences, no explanation.
Output path: .env.example`;
  }

  if (fixId === "vitest-ai") {
    const mockNote = mockingInstruction(files);
    return `You are a test engineer working on a ${fw} project.${repoUrl ? " " + repoNote : ""}

Write Vitest unit tests that test real code — NOT a smoke test like \`expect(true).toBe(true)\`.
Requirements:
- Several real source files are shown below — write tests for the actual exported
  components/hooks/functions in EACH of them, using their real file paths for imports
- Import the source files with ESM \`import\` (not \`require\`), and drop the \`.ts\`/\`.js\`
  extension entirely (e.g. \`import { foo } from "../src/utils"\`) — the source is TypeScript,
  never compiled to \`.js\` before tests run, so an extensioned \`require(".../file.js")\` call
  fails with "Cannot find module" even though the test logic itself is correct
- STRUCTURE: one top-level \`describe\` block per source file, named after the file path
  (e.g. \`describe("src/lib/utils.ts", () => { ... })\`). This keeps the output
  organized even though it is one file — never collapse all tests into a single flat list.
- For EACH exported unit under test, cover both the success path AND at least one failure/edge
  case (empty input, error thrown, falsy/null value) — not just the happy path
- Test environment: ${isReact ? "jsdom" : "node"}
- Use \`it\` blocks per scenario within each describe
- If there are more than 3-4 source files, a complete, well-formed file covering the most
  important ones beats a truncated file that started covering all of them — stop adding new
  \`describe\` blocks once you are running low on room, and never end mid-statement${mockNote}${ctx}

Return ONLY the TypeScript test file content. No markdown fences, no explanation.
Output path: tests/unit.test.ts`;
  }

  if (fixId === "pytest-ai") {
    return `You are a test engineer working on a Python ${fw} project.${repoUrl ? " " + repoNote : ""}

Write pytest tests that test real code — NOT smoke tests like \`assert True\`.
Requirements:
- Several real source files are shown below — write tests for actual functions/classes in EACH
- One top-level \`class Test<Module>:\` or \`def test_<function>_\` per source file
- Cover success paths AND at least one failure/edge case per unit
- Use pytest fixtures only when setup is genuinely shared
- Prefer plain \`assert\` — no placeholder comments${ctx}

Return ONLY the Python test file content. No markdown fences, no explanation.
Output path: tests/test_app.py`;
  }

  if (fixId === "go-test-ai") {
    return `You are a test engineer working on a Go ${fw} project.${repoUrl ? " " + repoNote : ""}

Write Go table-driven tests using the standard \`testing\` package — NOT empty \`t.Skip\` placeholders.
Requirements:
- Test real exported functions from the source files shown below
- One \`func Test<Name>(t *testing.T)\` per major unit, with \`t.Run\` subtests for scenarios
- Cover success AND at least one error/edge case per unit
- Use \`package <same_as_source>_test\` or same package if unexported symbols must be tested
- Import the packages under test using the module path declared in go.mod (shown below) —
  never derive an import path from the repository URL${ctx}

Return ONLY the Go test file content. No markdown fences, no explanation.
Output path: app_test.go`;
  }

  if (fixId === "rspec-ai") {
    return `You are a test engineer working on a Ruby ${fw} project.${repoUrl ? " " + repoNote : ""}

Write RSpec examples that test real application code — NOT \`expect(true).to be true\`.
Requirements:
- Several real source files are shown below — write \`describe\` blocks per class/module
- Use \`it\` blocks with real assertions on return values or side effects
- Cover happy path AND at least one failure/edge case per unit${ctx}

Return ONLY the Ruby spec file content. No markdown fences, no explanation.
Output path: spec/app_spec.rb`;
  }

  if (fixId === "phpunit-ai") {
    return `You are a test engineer working on a PHP ${fw} project.${repoUrl ? " " + repoNote : ""}

Write PHPUnit tests for real application classes — NOT empty test bodies.
Requirements:
- Several real source files are shown below — one test class per application class
- Use \`$this->assert*\` methods with meaningful expectations
- Cover success AND at least one error/edge case per unit${ctx}

Return ONLY the PHP test file content. No markdown fences, no explanation.
Output path: tests/AppTest.php`;
  }

  if (fixId === "junit-ai") {
    return `You are a test engineer working on a Java ${fw} project.${repoUrl ? " " + repoNote : ""}

Write JUnit 5 tests for real application classes — NOT empty @Test methods.
Requirements:
- Several real source files are shown below — one test class per production class
- The repo may already have its own test suite (not shown) — every generated test class name
  MUST end in \`GeneratedTest\` so it can never redeclare an existing test class (a duplicate
  class in the same package breaks the whole test compilation)
- Use JUnit 5 (\`org.junit.jupiter.api.*\`) with \`@Test\`, \`assertEquals\`, \`assertThrows\` as appropriate
- Match the build tool shown (Maven → src/test/java/...Test.java, Gradle → same layout)
- Cover success AND at least one failure/edge case per unit
- Use Mockito only if the source already uses dependency injection worth mocking${ctx}

Return ONLY the Java test file content. No markdown fences, no explanation.
Output path: src/test/java/AppTest.java`;
  }

  if (fixId === "cargo-test-ai") {
    return `You are a test engineer working on a Rust ${fw} project.${repoUrl ? " " + repoNote : ""}

Write Rust unit/integration tests — NOT empty \`#[test]\` bodies or \`todo!()\`.
Requirements:
- Test real functions/types from the source files shown below
- Prefer integration tests in \`tests/\` when testing public API; use \`#[cfg(test)] mod tests\` only for small internal units
- Use \`#[test]\` with \`assert_eq!\`, \`assert!\`, \`assert_matches!\` as appropriate
- Cover success AND at least one error/edge case per unit${ctx}

Return ONLY the Rust test file content. No markdown fences, no explanation.
Output path: tests/integration_test.rs`;
  }

  if (fixId === "xunit-ai") {
    return `You are a test engineer working on a C# ${fw} project.${repoUrl ? " " + repoNote : ""}

Write xUnit tests for real application classes — NOT empty [Fact] methods.
Requirements:
- Several real source files are shown below — one test class per production class
- Use xUnit (\`[Fact]\`, \`Assert.Equal\`, \`Assert.Throws\`) with .NET 8 patterns
- Place tests in a \`Tests\` project or \`tests/\` folder matching the .csproj layout shown
- Cover success AND at least one failure/edge case per unit${ctx}

Return ONLY the C# test file content. No markdown fences, no explanation.
Output path: tests/AppTests.cs`;
  }

  if (fixId === "exunit-ai") {
    return `You are a test engineer working on an Elixir ${fw} project.${repoUrl ? " " + repoNote : ""}

Write ExUnit tests for real application modules — NOT empty \`test\` blocks or \`assert true\`.
Requirements:
- Several real source files are shown below — one \`describe\`/\`test\` block per module
- The repo may already have its own test suite — name every generated test module with a
  \`GeneratedTest\` suffix (e.g. \`Chat.MessageGeneratedTest\`) so it never redefines an
  existing test module
- Reference modules EXACTLY as defined in the source files (\`defmodule\` lines) and take the
  app name from mix.exs shown below — never derive names from the repository URL
- Use \`ExUnit.Case\`, \`use AppWeb.ConnCase\` for Phoenix controllers when appropriate
- Use \`assert\`, \`assert_raise\`, \`refute\` with meaningful expectations
- Cover success AND at least one error/edge case per unit${ctx}

Return ONLY the Elixir test file content. No markdown fences, no explanation.
Output path: test/app_test.exs`;
  }

  if (fixId === "dart-test-ai") {
    return `You are a test engineer working on a Flutter/Dart ${fw} project.${repoUrl ? " " + repoNote : ""}

Write Flutter tests using \`flutter_test\` — NOT \`expect(true, true)\` or empty \`testWidgets\`.
Requirements:
- Several real Dart source files are shown below — widget tests for UI, unit tests for logic
- Import project code as \`package:<name>/...\` where <name> is the \`name:\` field of
  pubspec.yaml shown below — never derive the package name from the repository URL
- Use \`testWidgets\` for widgets with \`pumpWidget\`, \`find\`, \`expect\` matchers
- Use \`test\` for pure Dart functions/classes
- Cover success AND at least one failure/edge case per unit${ctx}

Return ONLY the Dart test file content. No markdown fences, no explanation.
Output path: test/app_test.dart`;
  }

  if (fixId === "swift-test-ai") {
    return `You are a test engineer working on a Swift ${fw} project.${repoUrl ? " " + repoNote : ""}

Write XCTest cases for real Swift code — NOT \`XCTAssertTrue(true)\` placeholders.
Requirements:
- Several real Swift source files are shown below — one test class or extension per module
- The repo may already have its own test suite (not shown) — every generated test class name
  MUST end in \`GeneratedTests\` so it can never redeclare an existing test class in the target
- Use \`XCTAssertEqual\`, \`XCTAssertThrowsError\`, \`XCTAssertNotNil\` with meaningful expectations
- For iOS/macOS apps, use \`@testable import\` when testing internal types — take the module or
  target name from Package.swift shown below (or the Sources/<Target>/ layout), never from the
  repository URL
- Cover success AND at least one failure/edge case per unit${ctx}

Return ONLY the Swift test file content. No markdown fences, no explanation.
Output path: Tests/AppTests.swift`;
  }

  if (fixId === "kotlin-test-ai") {
    return `You are a test engineer working on a Kotlin ${fw} project.${repoUrl ? " " + repoNote : ""}

Write Kotlin tests using JUnit 5 (preferred) or JUnit 4 — NOT empty \`@Test\` bodies or \`assertTrue(true)\`.
Requirements:
- Several real Kotlin source files are shown below — one test class per production class
- The repo may already have its own test suite (not shown) — every generated test class name
  MUST end in \`GeneratedTest\` so it can never redeclare an existing test class (a name
  collision in the same package breaks the whole test compilation)
- For Android: use \`src/test/java/\` for unit tests; reference AndroidX test APIs only if already in build.gradle
- For JVM/Ktor/Spring: match existing test dependencies from build files in context
- Use \`@Test\`, \`assertEquals\`, \`assertThrows\` with meaningful expectations
- Cover success AND at least one failure/edge case per unit${ctx}

Return ONLY the Kotlin test file content. No markdown fences, no explanation.
Output path: src/test/java/AppTest.kt`;
  }

  if (fixId === "playwright-ai") {
    const pwInput = playwrightInputFromFiles(files);
    const pwTarget = resolvePlaywrightTarget(pwInput);
    const primaryDev = resolveDevScript(pwInput.scripts ?? {});
    const stackLabel = files["__framework"] ?? fw;
    const webNote =
      primaryDev !== pwTarget.devScript
        ? ` (webServer uses shell command — npm "${primaryDev}" needs extra services)`
        : "";
    return `You are a test engineer working on a ${stackLabel} project (${files["__language"] ?? "node"}).${repoUrl ? " " + repoNote : ""}

Write Playwright end-to-end tests for public pages only — tests must pass on first run.
Requirements:
- Read the route/component files below — only assert elements that literally exist in the JSX
- Use \`page.goto("/route")\` (relative paths). Do NOT define a BASE_URL constant
- Use \`getByRole("heading")\` only for real h1–h6 tags; plan names / labels in div/span → \`getByText\`
- Do not assume Radix \`data-state\` — if accordion is custom useState buttons, test questions are visible, not expand/collapse
- Match exact link text from source (e.g. "Go home" not "Home")
- If cookie/beta banners may block clicks, add a small \`dismissOverlays(page)\` helper at the top
- Skip auth-gated routes, Stripe checkout, and OAuth unless fixtures are shown in the files
- 3–6 smoke tests max: home, one nav flow, one inner page, 404 if a notFound component exists
- webServer runs \`${pwTarget.runCommand}\` on ${pwTarget.baseUrl}${webNote}${ctx}

Return ONLY the TypeScript test file content. No markdown fences, no explanation.
Output path: e2e/main.spec.ts`;
  }

  if (fixId === "auditor-api-validation") {
    const target = files["__auditor_target"] ?? "the API route file";
    const lang =
      files["__language"] ??
      (target.endsWith(".py") ? "python" : target.endsWith(".java") ? "java" : "node");
    const validationHint =
      lang === "python"
        ? "Validate bodies/params with Pydantic models (`BaseModel`, `Field`) or the project's existing validation library"
        : lang === "java"
          ? "Validate request DTOs with `@Valid`, `@NotNull`, `@NotBlank`, or Jakarta Bean Validation"
          : "Validate with Zod (preferred) or the project's existing validation library (Joi, express-validator, etc.)";
    return `You are a backend engineer adding request validation to a ${fw} project.${repoUrl ? " " + repoNote : ""}

Patch \`${target}\` to validate incoming request bodies/params:
- ${validationHint}
- Return 400 with a clear error message on validation failure
- Do not change successful response shapes
- Check the other files shown below first — if a function this route calls already validates the
  same fields, do NOT add a second, redundant validation layer in this file${ctx}

Return ONLY the complete modified file for \`${target}\`. No markdown fences, no explanation.
Output path: ${target}`;
  }

  if (fixId === "auditor-auth-routes") {
    const target = files["__auditor_target"] ?? "the protected route";
    return `You are a security engineer adding authentication guards to a ${fw} project.${repoUrl ? " " + repoNote : ""}

Patch \`${target}\` so unauthenticated users cannot access this route:
- Use the project's existing auth pattern if visible in other files (NextAuth, Clerk, Supabase, custom session, etc.)
- Redirect or return 401/403 when no valid session
- Do not break public routes in the same file
- Check the other files shown below first — if a function this route calls already enforces auth
  internally, do NOT add a second, redundant auth check in this file${ctx}

Return ONLY the complete modified file for \`${target}\`. No markdown fences, no explanation.
Output path: ${target}`;
  }

  if (fixId === "auditor-localhost-api") {
    const target = files["__auditor_target"] ?? "the config file";
    const lang =
      files["__language"] ??
      (target.endsWith(".py") ? "python" : target.endsWith(".java") ? "java" : "node");
    const envHint =
      lang === "python"
        ? "Use `os.getenv` / `os.environ` for backend URLs and document vars in comments"
        : lang === "java"
          ? "Use `System.getenv` or Spring `@Value` and document vars in comments"
          : "Use `import.meta.env.VITE_*` for Vite, `process.env.NEXT_PUBLIC_*` for Next.js, or `process.env.*` for Node";
    return `You are a launch engineer removing hardcoded localhost API URLs from a ${fw} project.${repoUrl ? " " + repoNote : ""}

Patch \`${target}\` to use environment variables instead of hardcoded \`localhost\` / \`127.0.0.1\` API URLs:
- ${envHint}
- Provide sensible fallbacks only for local development
- Document new env vars in comments${ctx}

Return ONLY the complete modified file for \`${target}\`. No markdown fences, no explanation.
Output path: ${target}`;
  }

  if (fixId === "auditor-prisma-migrations") {
    return `You are a DevOps engineer making Prisma migrations production-safe for a ${fw} project.${repoUrl ? " " + repoNote : ""}

Update package.json scripts (and add a short prisma/MIGRATIONS.md only if helpful) so deploys run migrations:
- Add \`"db:migrate:deploy": "prisma migrate deploy"\` (or equivalent) if missing
- Add \`"postinstall": "prisma generate"\` only if prisma is a dependency and generate is not already covered
- Do not remove existing scripts${ctx}

Return ONLY the complete package.json content. No markdown fences, no explanation.
Output path: package.json`;
  }

  const mockNote = mockingInstruction(files);
  const lang = files["__language"] ?? "node";

  if (lang === "python") {
    return `You are a test engineer writing API integration tests for a Python ${fw} project.${repoUrl ? " " + repoNote : ""}

Write pytest tests for the main API routes/handlers — NOT placeholder assertions.
Requirements:
- Use FastAPI TestClient or Flask test client based on what the source files show
- Several real route/view files are shown below — test actual endpoints (method + path)
- For EACH endpoint: success status AND at least one error case from the handler code
- Use \`describe\`-style comments or class grouping per module${mockNote}${ctx}

Return ONLY the Python test file content. No markdown fences, no explanation.
Output path: tests/test_api.py`;
  }

  if (lang === "go") {
    return `You are a test engineer writing HTTP handler tests for a Go ${fw} project.${repoUrl ? " " + repoNote : ""}

Write Go tests using \`net/http/httptest\` for the handlers shown below — NOT empty tests.
Requirements:
- One \`func Test<Handler>(t *testing.T)\` per route/handler file
- Build requests with httptest.NewRequest and record with httptest.NewRecorder
- Assert status codes and response body for success AND error cases${mockNote}${ctx}

Return ONLY the Go test file content. No markdown fences, no explanation.
Output path: api_test.go`;
  }

  if (lang === "ruby") {
    return `You are a test engineer writing request specs for a Ruby ${fw} project.${repoUrl ? " " + repoNote : ""}

Write RSpec request specs for the controllers/routes shown below — NOT placeholder examples.
Requirements:
- Use rack-test or Rails request helpers based on what the project uses
- Test real HTTP methods and paths from the source files
- Cover success and at least one error response per endpoint${mockNote}${ctx}

Return ONLY the Ruby spec file content. No markdown fences, no explanation.
Output path: spec/requests/api_spec.rb`;
  }

  if (lang === "php") {
    return `You are a test engineer writing API tests for a PHP ${fw} project.${repoUrl ? " " + repoNote : ""}

Write PHPUnit feature tests for the routes/controllers shown below.
Requirements:
- Use Laravel's $this->get/post helpers or Symfony's WebTestCase based on the project
- Test real routes with meaningful status and JSON assertions${mockNote}${ctx}

Return ONLY the PHP test file content. No markdown fences, no explanation.
Output path: tests/Feature/ApiTest.php`;
  }

  if (lang === "java") {
    return `You are a test engineer writing API tests for a Java ${fw} project.${repoUrl ? " " + repoNote : ""}

Write JUnit 5 + MockMvc (Spring) or JAX-RS test client tests based on what the project uses.
Requirements:
- Test real REST endpoints from the controller files shown below
- Assert HTTP status codes and response body fields
- Cover success AND at least one error case per endpoint${mockNote}${ctx}

Return ONLY the Java test file content. No markdown fences, no explanation.
Output path: src/test/java/ApiIntegrationTest.java`;
  }

  if (lang === "rust") {
    return `You are a test engineer writing API integration tests for a Rust ${fw} project.${repoUrl ? " " + repoNote : ""}

Write integration tests using the project's HTTP stack (axum::test, actix_web::test, or reqwest against a test server).
Requirements:
- Test real routes/handlers from the source files shown below
- Assert status codes and JSON bodies with meaningful expectations${mockNote}${ctx}

Return ONLY the Rust test file content. No markdown fences, no explanation.
Output path: tests/api_integration.rs`;
  }

  return `You are a test engineer working on a ${fw} API.${repoUrl ? " " + repoNote : ""}

Write API integration tests for the main routes — NOT placeholder assertions.
Requirements:
- Several real route/handler files are shown below — test actual endpoints
- For TanStack Start / fetch handlers: import handlers or use fetch against a test server
- For Express: use Supertest with \`import app from "../src/app"\`
- For EACH endpoint: success status AND at least one error case
- Use \`describe\` blocks per route file, \`it\` blocks per scenario${mockNote}${ctx}

Return ONLY the TypeScript test file content. No markdown fences, no explanation.
Output path: tests/api.test.ts`;
}

// Generates a playwright.config.ts that boots the app before running tests.
// Without this, generated E2E tests fail immediately on repos that don't already have a config.

// Detects real external-call patterns (HTTP clients, DB/ORM clients) in the actual source
// samples already gathered — used to tell the model to mock these instead of letting generated
// tests silently hit real networks/databases.
function mockingInstruction(files: Record<string, string>): string {
  const sourceContent = Object.entries(files)
    .filter(([p]) => !p.startsWith("__"))
    .map(([, c]) => c)
    .join("\n");
  const pattern =
    /\bfetch\(|axios\.|\bky\.|\.from\(["'`]|new\s+(Pool|Client)\(|mongoose\.|prisma\.|supabase/;
  if (!pattern.test(sourceContent)) return "";
  return "\n- The source above makes real network/database calls — mock those (vi.mock / vi.fn / msw) so tests don't depend on a live network or database";
}

// Derived from the source of every function that shapes prompt output — editing wording or the
// deterministic facts fed into it changes this hash automatically, invalidating every
// ai_test_cache row written under the old version. No one has to remember to bump it by hand.
const PROMPT_VERSION = createHash("sha256")
  .update(
    buildPrompt.toString() +
      extractReadmeFacts.toString() +
      mockingInstruction.toString() +
      buildDeterministicCiWorkflow.toString() +
      buildProjectContext.toString() +
      projectContextToAiFiles.toString() +
      buildPlaywrightConfig.toString() +
      resolvePlaywrightTarget.toString() +
      resolveWebServerScript.toString() +
      resolveDevScript.toString() +
      playwrightInputFromFiles.toString() +
      "deterministic-ci-ai-v7-intelligence-auditor-fixes-v7-todo-report-cached",
  )
  .digest("hex")
  .slice(0, 12);

export function outputPath(fixId: string, files?: Record<string, string>): string {
  if (isAuditorFixId(fixId) && files) return auditorOutputPath(fixId, files);
  if (fixId === "ci-ai") return ".github/workflows/ci.yml";
  if (fixId === "readme-ai") return "README.md";
  if (fixId === "env-example-ai") return ".env.example";
  if (fixId === "vitest-ai") return "tests/unit.test.ts";
  if (fixId === "playwright-ai") return "e2e/main.spec.ts";
  if (fixId === "pytest-ai") return "tests/test_app.py";
  if (fixId === "go-test-ai") return "app_test.go";
  if (fixId === "rspec-ai") return "spec/app_spec.rb";
  if (fixId === "phpunit-ai") return "tests/AppTest.php";
  if (fixId === "junit-ai") return "src/test/java/AppTest.java";
  if (fixId === "cargo-test-ai") return "tests/integration_test.rs";
  if (fixId === "xunit-ai") return "tests/AppTests.cs";
  if (fixId === "exunit-ai") return "test/app_test.exs";
  if (fixId === "dart-test-ai") return "test/app_test.dart";
  if (fixId === "swift-test-ai") return "Tests/AppTests.swift";
  if (fixId === "kotlin-test-ai") return "src/test/java/AppTest.kt";
  if (fixId === "api-tests") {
    const lang = files?.["__language"] ?? "node";
    if (lang === "python") return "tests/test_api.py";
    if (lang === "go") return "api_test.go";
    if (lang === "ruby") return "spec/requests/api_spec.rb";
    if (lang === "php") return "tests/Feature/ApiTest.php";
    if (lang === "java") return "src/test/java/ApiIntegrationTest.java";
    if (lang === "kotlin") return "src/test/java/ApiIntegrationTest.kt";
    if (lang === "rust") return "tests/api_integration.rs";
    if (lang === "dart") return "test/api_test.dart";
    if (lang === "swift") return "Tests/ApiTests.swift";
  }
  return "tests/api.test.ts";
}

export function taskTypeForFix(fixId: string): TaskType {
  switch (fixId) {
    case "ci-ai":
      return "ci_generation";
    case "readme-ai":
      return "readme_improvements";
    case "env-example-ai":
      return "env_example_generation";
    case "vitest-ai":
    case "pytest-ai":
    case "go-test-ai":
    case "rspec-ai":
    case "phpunit-ai":
    case "junit-ai":
    case "cargo-test-ai":
    case "xunit-ai":
    case "exunit-ai":
    case "dart-test-ai":
    case "swift-test-ai":
    case "kotlin-test-ai":
      return "vitest_generation";
    case "playwright-ai":
      return "playwright_generation";
    case "auditor-api-validation":
    case "auditor-auth-routes":
    case "auditor-localhost-api":
    case "auditor-prisma-migrations":
      return "refactoring_suggestions";
    default:
      return "api_test_generation";
  }
}

// Post-process the raw AI response for a todo-markers fix:
// 1. Strip any markdown fences + explanation text the model added despite instructions.
// 2. Reject if the result lost >40% of the original lines (model deleted the file).
// 3. Reject if the result still starts with non-code prose.
function cleanTodoFixOutput(raw: string, original: string, actualLineCount = 0): string | null {
  let text = raw;

  // Strip markdown fences (```ts ... ``` or plain ```)
  const fenceRe = /^```[a-z]*\n/m;
  const fenceMatch = text.match(fenceRe);
  if (fenceMatch?.index !== undefined) {
    const afterFence = text.slice(fenceMatch.index + fenceMatch[0].length);
    const closingIdx = afterFence.lastIndexOf("\n```");
    if (closingIdx !== -1) {
      text = afterFence.slice(0, closingIdx);
    }
  }

  // Strip any leading prose lines before the first code line
  const codeLineRe =
    /^(import |export |const |let |var |function |class |interface |type |\/\/|\/\*|# |from |package |use |pub |fn |def |module |@[a-zA-Z]|<[a-zA-Z])/m;
  const codeStart = text.match(codeLineRe);
  if (codeStart?.index !== undefined && codeStart.index > 0) {
    text = text.slice(codeStart.index);
  }

  text = text.trimEnd() + "\n";

  // Reject if the model deleted most of the file.
  // Use the larger of (passed original, stored actual) so truncated inputs don't fool the guard.
  const originalLineCount = Math.max(original.split("\n").length, actualLineCount);
  const resultLineCount = text.split("\n").length;
  if (resultLineCount < originalLineCount * 0.6) return null;

  return text;
}

export interface AiTestFile {
  fixId: string;
  path: string;
  content: string;
}

// bypassCache: set to true when the user explicitly requested a new attempt (regenerate flow) —
// always hits the AI fresh, never reads from or writes to the shared cache, so a re-run without
// feedback doesn't silently return the same output the user already rejected, and feedback-steered
// results don't pollute the cache for other users.
export async function generateAiTests(
  scanId: string,
  fixIds: string[],
  fullName: string,
  token: string,
  framework?: string,
  feedback?: string,
  bypassCache = false,
): Promise<AiTestFile[]> {
  const db = getDataStore();
  const sortedKey = [...fixIds].sort().join(",");
  const skipCache = bypassCache || !!feedback;

  if (!skipCache) {
    const { data: scanCached } = await db
      .from("ai_test_cache")
      .select("result")
      .eq("scan_id", scanId)
      .eq("fix_ids", sortedKey)
      .eq("prompt_version", PROMPT_VERSION)
      .maybeSingle();
    if (scanCached) return JSON.parse(scanCached.result) as AiTestFile[];
  }

  const repoUrl = `https://github.com/${fullName}`;
  const relevantFiles = await fetchRelevantFiles(token, fullName, fixIds, framework);
  const contentHash = hashFiles(relevantFiles, fixIds);

  if (!skipCache) {
    const { data: hashCached } = await db
      .from("ai_test_cache")
      .select("result")
      .eq("content_hash", contentHash)
      .eq("prompt_version", PROMPT_VERSION)
      .maybeSingle();
    if (hashCached) {
      await db.from("ai_test_cache").insert({
        id: crypto.randomUUID(),
        scan_id: scanId,
        fix_ids: sortedKey,
        result: hashCached.result,
        content_hash: contentHash,
        prompt_version: PROMPT_VERSION,
      });
      return JSON.parse(hashCached.result) as AiTestFile[];
    }
  }

  const results: AiTestFile[] = [];

  // Phase 2 knowledge read path — inject into single-shot AI fixes (not only multi-agent).
  let repoKnowledge = "";
  try {
    const { data: scanRow } = await db
      .from("scans")
      .select("repo_id")
      .eq("id", scanId)
      .maybeSingle();
    if (scanRow?.repo_id) {
      const { loadRepoKnowledgeContext } = await import("./knowledge/writer.server");
      repoKnowledge = await loadRepoKnowledgeContext(scanRow.repo_id);
    }
  } catch (e) {
    console.error("[ai-tests] repo knowledge load failed:", e);
  }

  for (const fixId of fixIds) {
    if (fixId === "auditor-todo-markers") {
      // Generate a TODO_REPORT.md — a safe, additive new file that consolidates all markers.
      // We do NOT edit existing source files: AI surgical edits are unreliable and risky.
      let todoFilePaths: string[] = [];
      try {
        todoFilePaths = JSON.parse(relevantFiles["__todo_files"] ?? "[]");
      } catch {
        todoFilePaths = [];
      }
      if (todoFilePaths.length === 0) continue;

      // Build a compact context block: file path + the comment lines that contain markers
      const TODO_COMMENT_RE =
        /^\s*(?:\/\/|#|\*|\/\*).*\b(TODO|FIXME|HACK|XXX|PLACEHOLDER|not\s+implemented|coming\s+soon)\b/im;
      const sections: string[] = [];
      for (const filePath of todoFilePaths) {
        const content = relevantFiles[filePath];
        if (!content) continue;
        const markerLines = content
          .split("\n")
          .map((line, i) => ({ line, n: i + 1 }))
          .filter(({ line }) => TODO_COMMENT_RE.test(line))
          .map(({ line, n }) => `  L${n}: ${line.trim()}`)
          .slice(0, 10)
          .join("\n");
        if (markerLines) sections.push(`### ${filePath}\n${markerLines}`);
      }

      const prompt = `You are a senior developer creating a structured TODO report for a ${framework ?? "TypeScript"} project.

Below are the incomplete implementation markers found across the codebase. Write a markdown file called TODO_REPORT.md that:
1. Has a short intro explaining these were found by an automated scan
2. Groups entries by file with a header for each file
3. For each marker line, writes: the line number, the original comment, and a one-sentence recommendation (implement it, delete it if stale, or link it to a ticket)
4. Ends with a "Next steps" section

Do NOT modify any source files. Output ONLY the markdown content. No code fences around the whole document.

${sections.join("\n\n")}`;

      const text = await aiService.generate(prompt, { taskType: "code", maxTokens: 3072, repoUrl });
      results.push({
        fixId,
        path: "TODO_REPORT.md",
        content: stripCodeFence(text).trimEnd() + "\n",
      });
      continue;
    }

    // These auditor fixes only make sense against a concrete file the scanner actually found
    // (a real route, a real protected page, a real Prisma schema). Without one, the model has
    // nothing grounded to patch and fabricates a generic, sometimes-invalid file instead — so
    // skip cleanly (same pattern as auditor-todo-markers above) rather than shipping a guess.
    if (
      (fixId === "auditor-api-validation" ||
        fixId === "auditor-auth-routes" ||
        fixId === "auditor-localhost-api") &&
      !relevantFiles["__auditor_target"]
    ) {
      continue;
    }
    if (fixId === "auditor-prisma-migrations" && !relevantFiles["prisma/schema.prisma"]) {
      continue;
    }

    if (fixId === "ci-ai" && shouldUseDeterministicCi(relevantFiles)) {
      const content = buildDeterministicCiWorkflow(relevantFiles, {
        framework,
        fixIds,
      });
      results.push({ fixId, path: outputPath(fixId, relevantFiles), content });
      continue;
    }

    const prompt = buildPrompt(fixId, relevantFiles, repoUrl, framework, feedback, repoKnowledge);
    const taskType = taskTypeForFix(fixId);
    // readme-ai gets a much bigger budget — it must reproduce the entire existing README verbatim
    // plus additions, not just author a short new file like ci.yml/.env.example. The test fixes
    // (vitest/playwright/api-tests) now get several real source files instead of one, so they
    // need more room to write coverage for all of them, not just the first.
    const maxTokens =
      fixId === "readme-ai"
        ? 6144
        : fixId === "ci-ai"
          ? 2560
          : fixId === "env-example-ai"
            ? 1536
            : [
                  "vitest-ai",
                  "playwright-ai",
                  "api-tests",
                  "pytest-ai",
                  "go-test-ai",
                  "rspec-ai",
                  "phpunit-ai",
                  "junit-ai",
                  "cargo-test-ai",
                  "xunit-ai",
                  "exunit-ai",
                  "dart-test-ai",
                  "swift-test-ai",
                  "kotlin-test-ai",
                ].includes(fixId)
              ? 3072
              : isAuditorFixId(fixId)
                ? 3072
                : 2048;
    // Empirically, the model occasionally returns empty content for a given prompt (seen on
    // reasoning-model routes where the reasoning phase can consume the response with nothing
    // left over) even though a retry with the identical prompt succeeds — so retry once before
    // giving up rather than showing the user a blank file.
    let text = await aiService.generate(prompt, { taskType, maxTokens, repoUrl });
    if (!text.trim()) {
      text = await aiService.generate(prompt, { taskType, maxTokens, repoUrl });
    }
    const outPath = outputPath(fixId, relevantFiles);
    text = stripEchoedOutputPath(text, outPath);
    let content =
      fixId === "ci-ai" ? finalizeCiWorkflow(text) : stripCodeFence(text).trimEnd() + "\n";

    // On large/complex repos the model sometimes runs out of budget mid-file (seen: a test
    // file cut off mid-word). One retry with a bigger budget resolves it without inflating
    // cost for the common case where the first attempt already fits comfortably.
    if (validateGeneratedFile(outPath, content).status === "invalid") {
      // The router's response cache keys on (provider, model, method, prompt) — not maxTokens —
      // so reusing the identical prompt here would just return the same truncated text back out
      // of cache instead of making a fresh call with more room. Force a cache bypass.
      const retryText = await aiService.generate(prompt, {
        taskType,
        maxTokens: Math.round(maxTokens * 2.2),
        repoUrl,
        cacheKey: `retry:${crypto.randomUUID()}`,
      });
      const strippedRetry = stripEchoedOutputPath(retryText, outPath);
      const retryContent =
        fixId === "ci-ai"
          ? finalizeCiWorkflow(strippedRetry)
          : stripCodeFence(strippedRetry).trimEnd() + "\n";
      if (validateGeneratedFile(outPath, retryContent).status !== "invalid") {
        content = retryContent;
      }
    }
    results.push({ fixId, path: outPath, content });
  }

  if (!skipCache) {
    await db.from("ai_test_cache").insert({
      id: crypto.randomUUID(),
      scan_id: scanId,
      fix_ids: sortedKey,
      result: JSON.stringify(results),
      content_hash: contentHash,
      prompt_version: PROMPT_VERSION,
    });
  }

  return results;
}

export async function hasAiTestCache(
  scanId: string,
  fixIds: string[],
  fullName?: string,
  token?: string,
  framework?: string,
): Promise<boolean> {
  if (fixIds.length === 0) return false;
  const db = getDataStore();
  const sortedKey = [...fixIds].sort().join(",");

  const { data: scanHit } = await db
    .from("ai_test_cache")
    .select("id")
    .eq("scan_id", scanId)
    .eq("fix_ids", sortedKey)
    .maybeSingle();
  if (scanHit) return true;

  if (fullName && token) {
    const relevantFiles = await fetchRelevantFiles(token, fullName, fixIds, framework);
    const contentHash = hashFiles(relevantFiles, fixIds);
    const { data: hashHit } = await db
      .from("ai_test_cache")
      .select("id")
      .eq("content_hash", contentHash)
      .eq("prompt_version", PROMPT_VERSION)
      .maybeSingle();
    if (hashHit) return true;
  }

  return false;
}
