version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "@typescript-eslint/*"
          - "typescript-eslint"
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    groups:
      oxc:
        patterns:
          - "oxc_*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
