import { createFileRoute, notFound } from "@tanstack/react-router";
import { getPublicLaunchReportFn } from "@/lib/api/launch-report.functions";
import { LaunchReportDocument } from "@/components/launch-report-document";
import { BrandWordmark } from "@/components/brand-wordmark";
import { ThemeToggle } from "@/components/theme-toggle";

export const Route = createFileRoute("/r/$token")({
  head: () => ({ meta: [{ title: "Launch Report — LaunchReadyy" }] }),
  component: PublicReportPage,
  loader: async ({ params }) => {
    const report = await getPublicLaunchReportFn({ data: { token: params.token } }).catch(
      () => null,
    );
    if (!report) throw notFound();
    return { report };
  },
});

function PublicReportPage() {
  const { report } = Route.useLoaderData();

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="print-hide sticky top-0 z-40 border-b border-border/60 bg-background/70 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4 sm:px-6">
          <a
            href="/"
            className="flex shrink-0 items-baseline gap-1.5 font-display text-base font-semibold"
          >
            <BrandWordmark size="nav" />
            <span className="text-xs font-medium text-muted-foreground">Shared report</span>
          </a>
          <ThemeToggle />
        </div>
      </header>

      <main className="mx-auto w-full max-w-4xl flex-1 px-4 py-6 sm:px-6">
        <LaunchReportDocument report={report} />
      </main>

      <footer className="print-hide border-t border-border/60 py-6 text-center text-xs text-muted-foreground">
        Generated by LaunchReadyy — a production readiness scan of a repository the owner chose to
        share.
      </footer>
    </div>
  );
}
