import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { REPO_URL } from "@/lib/product";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [{ title: "Terms — LaunchReadyy" }],
  }),
  component: TermsPage,
});

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-8 font-display text-lg font-semibold text-foreground">{children}</h2>;
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-3 leading-relaxed">{children}</p>;
}

function TermsPage() {
  return (
    <div className="min-h-screen">
      <SiteHeader />
      <article className="mx-auto max-w-3xl px-6 py-12 text-sm text-muted-foreground">
        <h1 className="font-display text-3xl font-semibold text-foreground">Terms</h1>
        <p className="mt-2 text-xs">Last updated: September 18, 2026</p>

        <P>
          LaunchReadyy Community is open-source, self-hosted software. There is no LaunchReadyy
          account to create and no LaunchReadyy server your code or data passes through. These terms
          cover running the software on infrastructure you control.
        </P>

        <H2>1. Your installation</H2>
        <P>
          You control access to your installation. Protect it with an authenticating reverse proxy
          if you expose it on a network, and don't misrepresent your affiliation with the project.
        </P>

        <H2>2. The software</H2>
        <P>
          The software itself is licensed under the terms in the repository's{" "}
          <a
            href={`${REPO_URL}/blob/main/LICENSE`}
            target="_blank"
            rel="noreferrer"
            className="text-primary hover:underline"
          >
            LICENSE
          </a>{" "}
          file, which governs how you may use, modify, and distribute it. If anything below
          conflicts with the LICENSE, the LICENSE controls.
        </P>
        <P>
          When you run LaunchReadyy, it runs entirely on your own machine or infrastructure, under
          your own GitHub token and (optionally) your own AI provider and E2B keys. You are the
          operator: you control what repositories it connects to, what data it stores in your local
          SQLite database, and what third-party services it talks to on your behalf. LaunchReadyy
          the project has no visibility into any of that and no ability to access, modify, or delete
          it.
        </P>
        <P>
          LaunchReadyy never pushes directly to a branch you didn't ask it to, deletes files, or
          takes destructive action on a connected repository — it opens pull requests for you to
          review and merge yourself. You are solely responsible for reviewing every pull request
          before merging it.
        </P>
        <P>
          The scoring, checklist items, and Production Security findings are advisory automation
          output — not a security audit, penetration test, or compliance certification, and not a
          guarantee that a repository is safe or ready for production.
        </P>

        <H2>3. Acceptable use</H2>
        <P>
          Only scan or fix repositories and domains you own or have explicit permission to test.
          Live website scans are passive checks only — don't use them, or the software generally,
          for unauthorized testing, exploitation, or attacks on any system.
        </P>

        <H2>4. No warranty</H2>
        <P>
          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT
          PERMITTED BY LAW, THE PROJECT AND ITS MAINTAINERS ARE NOT LIABLE FOR ANY DAMAGES ARISING
          FROM YOUR USE OF THE SOFTWARE, INCLUDING ANY CONTENT GENERATED BY THE SOFTWARE THAT YOU
          CHOOSE TO MERGE INTO YOUR OWN PROJECTS.
        </P>

        <H2>5. Trademarks</H2>
        <P>
          "LaunchReadyy" and its logo identify this project. Using the open-source code doesn't by
          itself grant permission to use the project name or logo for a modified distribution in a
          way that implies endorsement or affiliation.
        </P>

        <H2>6. Changes</H2>
        <P>
          We may update these Terms from time to time; the date above reflects the latest revision.
          Material changes will be noted in the repository's changelog.
        </P>

        <H2>7. Contact</H2>
        <P>
          Questions:{" "}
          <a href="mailto:launchreadyy@gmail.com" className="text-primary hover:underline">
            launchreadyy@gmail.com
          </a>{" "}
          or{" "}
          <a
            href={`${REPO_URL}/issues`}
            target="_blank"
            rel="noreferrer"
            className="text-primary hover:underline"
          >
            open an issue
          </a>
          .
        </P>
        <P>
          See also:{" "}
          <Link to="/privacy" className="text-primary hover:underline">
            Privacy
          </Link>
          .
        </P>
      </article>
      <SiteFooter />
    </div>
  );
}
