// Split from fix-executor.server.ts — behavior-preserving.

import { validateGeneratedFile } from "../fix-validation";
import type { AiTestFile, PreviewDiffLine, PreviewFileDiff, VerificationNote } from "./types";
import {
  ghGet,
  createOrUpdateBranch,
  createCommitOnBranchGQL,
  createTree,
  createCommit,
  ensureBranch,
  ensureBranchGQL,
  getRepoNodeId,
  getBranchHeadOid,
  commitFilesViaContentsApi,
  openPullRequest,
  fetchFileContent,
} from "./github";
import { collectFixFiles, FIX_LABEL, FIX_WHY } from "./body";
import { SANDBOX_VERIFY_FIX_ID, unverifiedBanner } from "./verification-notes";

// ─── PR creation from pre-generated files ────────────────────────────────────

export async function createPRFromFiles(
  token: string,
  repoFullName: string,
  defaultBranch: string,
  branchName: string,
  fixIds: string[],
  files: { path: string; content: string }[],
  verificationNotes?: VerificationNote[],
  framework?: string,
): Promise<{ prNumber: number; prUrl: string }> {
  if (!files.length) throw new Error("No files to commit.");

  const { assertGitHubRepoWriteAccess } = await import("../github.server");
  await assertGitHubRepoWriteAccess(token, repoFullName);

  const repoMeta = await ghGet<{ full_name: string; default_branch: string }>(
    token,
    `/repos/${repoFullName}`,
  );
  const fullName = repoMeta.full_name;
  const baseBranch = repoMeta.default_branch || defaultBranch;

  const refData = await ghGet<{ object: { sha: string } }>(
    token,
    `/repos/${fullName}/git/ref/heads/${baseBranch}`,
  );
  const baseSha = refData.object.sha;

  const commitData = await ghGet<{ tree: { sha: string } }>(
    token,
    `/repos/${fullName}/git/commits/${baseSha}`,
  );
  const baseTreeSha = commitData.tree.sha;

  const labels = fixIds.map((id) => FIX_LABEL[id] ?? id);
  const commitMessage = `chore: add production setup\n\nAdded: ${labels.join(", ")}\n\nGenerated by LaunchReadyy`;

  const normalizedFiles = files.map((f) => ({
    path: f.path.replace(/^\/+/, ""),
    content: f.content,
  }));

  const [owner, repoName] = fullName.split("/");

  // ── Primary: GitHub GraphQL createCommitOnBranch ────────────────────────────
  // Goes through a different server path than the REST git objects API.
  try {
    const repoId = await getRepoNodeId(token, owner, repoName);
    await ensureBranchGQL(token, repoId, branchName, baseSha);
    const headOid = (await getBranchHeadOid(token, owner, repoName, branchName)) ?? baseSha;
    await createCommitOnBranchGQL(
      token,
      owner,
      repoName,
      branchName,
      headOid,
      normalizedFiles,
      commitMessage,
    );
  } catch (gqlErr) {
    const gqlMsg = gqlErr instanceof Error ? gqlErr.message : String(gqlErr);

    // ── Fallback 1: REST git trees API ────────────────────────────────────────
    let treesErr: unknown;
    try {
      const newTreeSha = await createTree(token, fullName, baseTreeSha, normalizedFiles);
      const newCommitSha = await createCommit(token, fullName, commitMessage, newTreeSha, baseSha);
      await createOrUpdateBranch(token, fullName, branchName, newCommitSha);
      treesErr = null;
    } catch (err) {
      treesErr = err;
    }

    if (treesErr) {
      // ── Fallback 2: Contents API (file-by-file) ────────────────────────────
      await ensureBranch(token, fullName, branchName, baseSha);
      try {
        await commitFilesViaContentsApi(
          token,
          fullName,
          branchName,
          normalizedFiles,
          commitMessage,
        );
      } catch (contentsErr) {
        const treesMsg = treesErr instanceof Error ? treesErr.message : String(treesErr);
        const contentsMsg =
          contentsErr instanceof Error ? contentsErr.message : String(contentsErr);
        throw new Error(
          `GraphQL commit failed: ${gqlMsg}\nGit Trees API failed: ${treesMsg}\nContents API fallback failed: ${contentsMsg}`,
        );
      }
    }
  }

  const titleSuffix =
    fixIds.length > 3
      ? `${fixIds
          .slice(0, 3)
          .map((id) => FIX_LABEL[id] ?? id)
          .join(", ")} +${fixIds.length - 3} more`
      : labels.join(", ");

  const prBody = buildPrBody({
    fixIds,
    files,
    verificationNotes,
    framework,
    baseBranch,
  });

  const pr = await openPullRequest(
    token,
    fullName,
    branchName,
    baseBranch,
    `chore: add production setup (${titleSuffix})`,
    prBody,
  );

  return { prNumber: pr.number, prUrl: pr.html_url };
}

/**
 * The pull request body, as pure data in and markdown out.
 *
 * Extracted from {@link createPRFromFiles} so the sandbox-verification disclosure can be tested
 * without standing up GitHub. Whether a PR admits it was never built is a safety property, and it
 * was previously expressed only inside a function that needs six network round-trips to reach.
 */
export function buildPrBody(input: {
  fixIds: string[];
  files: { path: string; content: string }[];
  verificationNotes?: VerificationNote[];
  framework?: string;
  baseBranch: string;
}): string {
  const { fixIds, files, verificationNotes, framework, baseBranch } = input;

  const verificationSection =
    verificationNotes && verificationNotes.length > 0
      ? [
          `## Verification`,
          ``,
          `| Fix | Status | Notes |`,
          `|-----|--------|-------|`,
          ...verificationNotes.map((n) => {
            // "needs manual step" is right for a fix awaiting setup, but wrong for a sandbox that
            // never ran — that is not a step the reader can take, it is a check we did not make.
            const status =
              n.status === "verified"
                ? "✅"
                : n.fixId === SANDBOX_VERIFY_FIX_ID
                  ? "⚠️ not verified"
                  : "⚠️ needs manual step";
            // Skip reasons can carry a provider error verbatim; a stray pipe would break the row.
            // Backslashes are escaped first, because doing it second would double the backslash
            // this step just added (`\|` → `\\|`) and the row would lose its separator — the
            // escape character has to be escaped before the character it escapes.
            const note = n.note.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
            return `| ${FIX_LABEL[n.fixId] ?? n.fixId} | ${status} | ${note} |`;
          }),
          ``,
        ]
      : [];

  const whyLines = fixIds
    .filter((id) => FIX_WHY[id])
    .map((id) => `- **${FIX_LABEL[id] ?? id}:** ${FIX_WHY[id]}`);

  const setupSteps: string[] = [];
  if (fixIds.includes("monitoring")) {
    const dsnVar = framework === "Vite" || framework === "React" ? "VITE_SENTRY_DSN" : "SENTRY_DSN";
    setupSteps.push(
      `### ⚠️ Action required: activate Sentry`,
      ``,
      `1. Sign up for a free account at [sentry.io](https://sentry.io)`,
      `2. Create a new project and copy your DSN`,
      `3. Add it to your environment variables:`,
      `   \`\`\``,
      `   ${dsnVar}=https://your-dsn@sentry.io/your-project-id`,
      `   \`\`\``,
      `4. Deploy — Sentry will start capturing errors immediately`,
      ``,
    );
  }

  const testStep = fixIds.some((id) => id.includes("vitest") || id.includes("test"))
    ? "2. Run `npm install` then `npm run lint` and `npm test`"
    : "2. Run `npm install` then `npm run lint`";

  const sandboxVerified = verificationNotes?.some(
    (n) => n.fixId === SANDBOX_VERIFY_FIX_ID && n.status === "verified",
  );
  // Why the sandbox did not run, when the caller recorded it. Absent on paths that never attempt
  // verification at all — those are equally unverified and must say so in the same words.
  const skipReason = verificationNotes?.find(
    (n) => n.fixId === SANDBOX_VERIFY_FIX_ID && n.status === "warning",
  )?.reason;

  return [
    `## Launch Readiness — production setup PR`,
    ``,
    `### Summary`,
    `${fixIds.length} production gap${fixIds.length > 1 ? "s" : ""} addressed. Review diffs before merge.`,
    sandboxVerified
      ? `\n_Verified: install/build/lint passed in an isolated LaunchReadyy sandbox before this PR was opened._\n`
      : unverifiedBanner(skipReason),
    `### What changed & why`,
    ...whyLines,
    ``,
    `### How to test`,
    `1. Check out this branch locally`,
    sandboxVerified
      ? `2. Sandbox already verified build/lint — still run locally if you prefer`
      : testStep,
    `3. Confirm CI passes on this PR`,
    ``,
    `### Rollback`,
    `Revert this PR merge commit on \`${baseBranch}\` if anything breaks post-deploy. No destructive migrations in this PR.`,
    ``,
    ...setupSteps,
    ...verificationSection,
    `<details><summary>Files changed (${files.length})</summary>`,
    ``,
    files.map((f) => `- \`${f.path}\``).join("\n"),
    ``,
    `</details>`,
    ``,
    `---`,
    `_Generated by [LaunchReadyy](https://github.com/g0GobliN/launchreadyy)_`,
  ].join("\n");
}

/** Commit file changes on top of an existing branch (no new PR). */
export async function commitFilesOnBranch(
  token: string,
  repoFullName: string,
  branchName: string,
  files: { path: string; content: string }[],
  commitMessage: string,
): Promise<void> {
  if (!files.length) throw new Error("No files to commit.");

  const { assertGitHubRepoWriteAccess } = await import("../github.server");
  await assertGitHubRepoWriteAccess(token, repoFullName);

  const repoMeta = await ghGet<{ full_name: string }>(token, `/repos/${repoFullName}`);
  const fullName = repoMeta.full_name;
  const normalizedFiles = files.map((f) => ({
    path: f.path.replace(/^\/+/, ""),
    content: f.content,
  }));
  const [owner, repoName] = fullName.split("/");

  try {
    const headOid = await getBranchHeadOid(token, owner, repoName, branchName);
    if (!headOid) throw new Error(`Branch ${branchName} not found on ${fullName}`);
    await createCommitOnBranchGQL(
      token,
      owner,
      repoName,
      branchName,
      headOid,
      normalizedFiles,
      commitMessage,
    );
  } catch (gqlErr) {
    try {
      await commitFilesViaContentsApi(token, fullName, branchName, normalizedFiles, commitMessage);
    } catch (contentsErr) {
      const gqlMsg = gqlErr instanceof Error ? gqlErr.message : String(gqlErr);
      const contentsMsg = contentsErr instanceof Error ? contentsErr.message : String(contentsErr);
      throw new Error(`Failed to commit on ${branchName}: ${gqlMsg}; ${contentsMsg}`);
    }
  }
}

/** Open an existing branch's PR, or create one if the branch has no open PR. */
export async function ensureOpenPullRequest(
  token: string,
  repoFullName: string,
  branchName: string,
  defaultBranch: string,
  fixIds: string[],
): Promise<{ prNumber: number; prUrl: string }> {
  const repoMeta = await ghGet<{ full_name: string; default_branch: string }>(
    token,
    `/repos/${repoFullName}`,
  );
  const fullName = repoMeta.full_name;
  const baseBranch = repoMeta.default_branch || defaultBranch;
  const labels = fixIds.map((id) => FIX_LABEL[id] ?? id);
  const titleSuffix =
    fixIds.length > 3
      ? `${fixIds
          .slice(0, 3)
          .map((id) => FIX_LABEL[id] ?? id)
          .join(", ")} +${fixIds.length - 3} more`
      : labels.join(", ");
  const pr = await openPullRequest(
    token,
    fullName,
    branchName,
    baseBranch,
    `chore: add production setup (${titleSuffix})`,
    [
      `## Launch Readiness — production setup PR`,
      ``,
      `Relaunched by LaunchReadyy after CI recovery.`,
      ``,
      `_Generated by [LaunchReadyy](https://github.com/g0GobliN/launchreadyy)_`,
    ].join("\n"),
  );
  return { prNumber: pr.number, prUrl: pr.html_url };
}

// ─── Main entry point ─────────────────────────────────────────────────────────

export async function executeFixJob(
  token: string,
  repoFullName: string,
  defaultBranch: string,
  branchName: string,
  fixIds: string[],
  opts?: { framework?: string; repoName?: string; aiFiles?: AiTestFile[] },
): Promise<{ prNumber: number; prUrl: string }> {
  const { files, verificationNotes } = await collectFixFiles(token, repoFullName, fixIds, opts);
  return createPRFromFiles(
    token,
    repoFullName,
    defaultBranch,
    branchName,
    fixIds,
    files,
    verificationNotes,
    opts?.framework,
  );
}

// ─── Preview diff computation ─────────────────────────────────────────────────

export type DiffLineType = "add" | "del" | "ctx" | "hunk";

export interface AnnotatedOp {
  type: "eq" | "add" | "del";
  line: string;
  oldNo: number;
  newNo: number;
}

/**
 * Ceiling on the LCS table, in cells.
 *
 * The table is quadratic, and computeDiffsFromFiles diffs every file concurrently, so a couple of
 * large files could exhaust a 128 MB Worker between them: two 3000-line versions of one file is
 * 9M cells. At 4 bytes per cell this cap is ~16 MB per file, which leaves room for several at
 * once. Past it, a precise diff is abandoned in favour of a whole-file replacement — the honest
 * rendering of "everything here changed", and far better than the isolate being killed.
 */
const MAX_LCS_CELLS = 4_000_000;

/** Every line of `a` removed, then every line of `b` added. Used when the table would be too big. */
function replaceAllOps(a: string[], b: string[]): AnnotatedOp[] {
  return [
    ...a.map((line, idx) => ({ type: "del" as const, line, oldNo: idx + 1, newNo: 0 })),
    ...b.map((line, idx) => ({ type: "add" as const, line, oldNo: 0, newNo: idx + 1 })),
  ];
}

export function lcsOps(a: string[], b: string[]): AnnotatedOp[] {
  const m = a.length,
    n = b.length;
  if ((m + 1) * (n + 1) > MAX_LCS_CELLS) return replaceAllOps(a, b);

  // Flat Int32Array rather than an array of arrays: same values, roughly half the bytes and none
  // of the per-row object overhead. dp[i][j] is dp[i * width + j].
  const width = n + 1;
  const dp = new Int32Array((m + 1) * width);
  for (let i = 1; i <= m; i++) {
    const row = i * width;
    const prev = row - width;
    for (let j = 1; j <= n; j++) {
      dp[row + j] =
        a[i - 1] === b[j - 1] ? dp[prev + j - 1] + 1 : Math.max(dp[prev + j], dp[row + j - 1]);
    }
  }

  const raw: { type: "eq" | "add" | "del"; line: string }[] = [];
  let i = m,
    j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
      raw.unshift({ type: "eq", line: a[i - 1] });
      i--;
      j--;
    } else if (j > 0 && (i === 0 || dp[i * width + j - 1] >= dp[(i - 1) * width + j])) {
      raw.unshift({ type: "add", line: b[j - 1] });
      j--;
    } else {
      raw.unshift({ type: "del", line: a[i - 1] });
      i--;
    }
  }

  let oldNo = 0,
    newNo = 0;
  return raw.map((op) => {
    if (op.type !== "add") oldNo++;
    if (op.type !== "del") newNo++;
    return { ...op, oldNo: op.type === "add" ? 0 : oldNo, newNo: op.type === "del" ? 0 : newNo };
  });
}

export function opsToPreviewLines(ops: AnnotatedOp[], context = 3): PreviewDiffLine[] {
  const changedIdxs = ops.map((op, i) => (op.type !== "eq" ? i : -1)).filter((i) => i >= 0);
  if (changedIdxs.length === 0) return [];

  const ranges: [number, number][] = [];
  for (const idx of changedIdxs) {
    const s = Math.max(0, idx - context);
    const e = Math.min(ops.length - 1, idx + context);
    if (ranges.length === 0 || s > ranges[ranges.length - 1][1] + 1) {
      ranges.push([s, e]);
    } else {
      ranges[ranges.length - 1][1] = Math.max(ranges[ranges.length - 1][1], e);
    }
  }

  const result: PreviewDiffLine[] = [];
  for (const [s, e] of ranges) {
    let oldCount = 0,
      newCount = 0;
    for (let k = s; k <= e; k++) {
      if (ops[k].type !== "add") oldCount++;
      if (ops[k].type !== "del") newCount++;
    }
    // Old/new starting line numbers for this hunk
    let oldStart = 0,
      newStart = 0;
    for (let k = 0; k < s; k++) {
      if (ops[k].type !== "add") oldStart = ops[k].oldNo;
      if (ops[k].type !== "del") newStart = ops[k].newNo;
    }
    oldStart += 1;
    newStart += 1;

    result.push({ type: "hunk", text: `@@ -${oldStart},${oldCount} +${newStart},${newCount} @@` });

    for (let k = s; k <= e; k++) {
      const op = ops[k];
      if (op.type === "eq") {
        result.push({ type: "ctx", text: op.line, oldNo: op.oldNo, newNo: op.newNo });
      } else if (op.type === "add") {
        result.push({ type: "add", text: op.line, newNo: op.newNo });
      } else {
        result.push({ type: "del", text: op.line, oldNo: op.oldNo });
      }
    }
  }
  return result;
}

export function newFileDiffLines(content: string): PreviewDiffLine[] {
  const lines = content.trimEnd().split("\n");
  const result: PreviewDiffLine[] = [{ type: "hunk", text: `@@ -0,0 +1,${lines.length} @@` }];
  lines.forEach((line, i) => result.push({ type: "add", text: line, newNo: i + 1 }));
  return result;
}

// Compute diffs from already-generated files (used when fix_cache is hit).
export async function computeDiffsFromFiles(
  token: string,
  fullName: string,
  proposed: { path: string; content: string }[],
): Promise<PreviewFileDiff[]> {
  const diffs = await Promise.all(
    proposed.map(async ({ path, content }) => {
      const validation = validateGeneratedFile(path, content);
      const original = await fetchFileContent(token, fullName, path);
      if (!original) {
        return { path, status: "added" as const, lines: newFileDiffLines(content), validation };
      }

      // A generated file that matches what is already committed changes nothing, so it must not
      // appear in the review at all. This previously fell through to newFileDiffLines, which
      // presented the whole existing file as freshly added under a `@@ -0,0 +1,N @@` header —
      // telling the operator an already-applied fix was about to add N lines and producing an
      // empty PR.
      if (original === content) return null;

      const ops = lcsOps(original.trimEnd().split("\n"), content.trimEnd().split("\n"));
      const lines = opsToPreviewLines(ops);
      // Non-empty only when the two differ beyond trailing whitespace; a trailing-newline-only
      // change is not worth showing, and certainly not worth showing as a full-file rewrite.
      if (lines.length === 0) return null;

      return { path, status: "modified" as const, lines, validation };
    }),
  );
  return diffs.filter((d): d is PreviewFileDiff => d !== null && d.lines.length > 0);
}

export async function computePreviewDiffs(
  token: string,
  fullName: string,
  fixIds: string[],
  opts?: { framework?: string; repoName?: string },
): Promise<PreviewFileDiff[]> {
  const { files } = await collectFixFiles(token, fullName, fixIds, opts);
  return computeDiffsFromFiles(token, fullName, files);
}
