#!/usr/bin/env node
/**
 * Concatenate docs/reference/*.md into docs/FULL_DOCUMENTATION.md.
 * Edit chapters in reference/ only — never hand-edit the generated file.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const refDir = join(root, "docs", "reference");
const outFile = join(root, "docs", "FULL_DOCUMENTATION.md");

/** Chapter order — add new chapters here. */
export const CHAPTERS = [
  "01-overview.md",
  "02-system-architecture.md",
  "03-technology-stack.md",
  "04-repository-layout.md",
  "05-frontend.md",
  "06-backend.md",
  "07-database.md",
  "08-authentication.md", // gitleaks:allow
  "09-costs-and-limits.md",
  "10-scan-system.md",
  "11-fix-system.md",
  "12-sandbox.md",
  "13-ai-layer.md",
  "14-api.md",
  "15-environment-variables.md",
  "16-security.md",
  "17-known-issues.md",
  "18-monitoring.md",
  "19-tool-licensing.md",
  "appendix-a-scripts.md",
  "appendix-b-ports.md",
];

const mode = process.argv[2] ?? "build";

function render(date = new Date().toISOString().slice(0, 10)) {
  const parts = [
    "# LaunchReadyy — Full documentation",
    "",
    "> **Generated.** Do not edit this file. Edit chapters in `docs/reference/`, then run `npm run docs:build`.",
    "",
    `Generated: ${date}`,
    "",
  ];

  for (const name of CHAPTERS) {
    const path = join(refDir, name);
    const body = readFileSync(path, "utf8").trimEnd();
    parts.push("---", "", body, "");
  }

  return parts.join("\n") + "\n";
}

function build() {
  writeFileSync(outFile, render());
  console.log(`Wrote ${outFile} (${CHAPTERS.length} chapters)`);
}

function normalize(s) {
  return s.replace(/^Generated: .+$/m, "Generated: DATE");
}

function check() {
  if (!existsSync(outFile)) {
    console.error("FULL_DOCUMENTATION.md missing. Run: npm run docs:build");
    process.exit(1);
  }
  const onDisk = readFileSync(outFile, "utf8");
  const expected = render("DATE");
  if (normalize(onDisk) !== normalize(expected)) {
    console.error("FULL_DOCUMENTATION.md is out of date. Run: npm run docs:build");
    process.exit(1);
  }
  console.log("docs:check OK");
}

function listMissing() {
  const onDisk = new Set(readdirSync(refDir).filter((f) => f.endsWith(".md")));
  for (const c of CHAPTERS) {
    if (!onDisk.has(c)) {
      console.error(`Missing chapter file: ${c}`);
      process.exit(1);
    }
  }
  for (const f of onDisk) {
    if (!CHAPTERS.includes(f)) {
      console.warn(`Warning: ${f} exists but is not in CHAPTERS order`);
    }
  }
}

listMissing();
if (mode === "check") check();
else build();
