/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoRepoIdRouteImport } from './routes/repo.$repoId'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as PrRepoIdRouteImport } from './routes/pr.$repoId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as RepoRepoIdIndexRouteImport } from './routes/repo.$repoId.index'
import { Route as RepoRepoIdReportRouteImport } from './routes/repo.$repoId_.report'
import { Route as RepoRepoIdLiveSecurityRouteImport } from './routes/repo.$repoId_.live-security'
import { Route as RepoRepoIdArchRouteImport } from './routes/repo.$repoId_.arch'
import { Route as RepoRepoIdSandboxRouteImport } from './routes/repo.$repoId.sandbox'
import { Route as RepoRepoIdRunsRouteImport } from './routes/repo.$repoId.runs'
import { Route as RepoRepoIdFixRouteImport } from './routes/repo.$repoId.fix'
import { Route as RepoRepoIdEnvRouteImport } from './routes/repo.$repoId.env'
import { Route as RepoRepoIdBlockersRouteImport } from './routes/repo.$repoId.blockers'
import { Route as RepoRepoIdJobJobIdRouteImport } from './routes/repo.$repoId.job.$jobId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdRoute = RepoRepoIdRouteImport.update({
  id: '/repo/$repoId',
  path: '/repo/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PrRepoIdRoute = PrRepoIdRouteImport.update({
  id: '/pr/$repoId',
  path: '/pr/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdIndexRoute = RepoRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdReportRoute = RepoRepoIdReportRouteImport.update({
  id: '/repo/$repoId_/report',
  path: '/repo/$repoId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdLiveSecurityRoute = RepoRepoIdLiveSecurityRouteImport.update({
  id: '/repo/$repoId_/live-security',
  path: '/repo/$repoId/live-security',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdArchRoute = RepoRepoIdArchRouteImport.update({
  id: '/repo/$repoId_/arch',
  path: '/repo/$repoId/arch',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdSandboxRoute = RepoRepoIdSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdRunsRoute = RepoRepoIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdFixRoute = RepoRepoIdFixRouteImport.update({
  id: '/fix',
  path: '/fix',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdEnvRoute = RepoRepoIdEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdBlockersRoute = RepoRepoIdBlockersRouteImport.update({
  id: '/blockers',
  path: '/blockers',
  getParentRoute: () => RepoRepoIdRoute,
} as any)
const RepoRepoIdJobJobIdRoute = RepoRepoIdJobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => RepoRepoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/jobs': typeof JobsRoute
  '/license': typeof LicenseRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/repos': typeof ReposRoute
  '/scans': typeof ScansRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pr/$repoId': typeof PrRepoIdRoute
  '/r/$token': typeof RTokenRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repo/$repoId/blockers': typeof RepoRepoIdBlockersRoute
  '/repo/$repoId/env': typeof RepoRepoIdEnvRoute
  '/repo/$repoId/fix': typeof RepoRepoIdFixRoute
  '/repo/$repoId/runs': typeof RepoRepoIdRunsRoute
  '/repo/$repoId/sandbox': typeof RepoRepoIdSandboxRoute
  '/repo/$repoId/arch': typeof RepoRepoIdArchRoute
  '/repo/$repoId/live-security': typeof RepoRepoIdLiveSecurityRoute
  '/repo/$repoId/report': typeof RepoRepoIdReportRoute
  '/repo/$repoId/': typeof RepoRepoIdIndexRoute
  '/repo/$repoId/job/$jobId': typeof RepoRepoIdJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/jobs': typeof JobsRoute
  '/license': typeof LicenseRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/repos': typeof ReposRoute
  '/scans': typeof ScansRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pr/$repoId': typeof PrRepoIdRoute
  '/r/$token': typeof RTokenRoute
  '/repo/$repoId/blockers': typeof RepoRepoIdBlockersRoute
  '/repo/$repoId/env': typeof RepoRepoIdEnvRoute
  '/repo/$repoId/fix': typeof RepoRepoIdFixRoute
  '/repo/$repoId/runs': typeof RepoRepoIdRunsRoute
  '/repo/$repoId/sandbox': typeof RepoRepoIdSandboxRoute
  '/repo/$repoId/arch': typeof RepoRepoIdArchRoute
  '/repo/$repoId/live-security': typeof RepoRepoIdLiveSecurityRoute
  '/repo/$repoId/report': typeof RepoRepoIdReportRoute
  '/repo/$repoId': typeof RepoRepoIdIndexRoute
  '/repo/$repoId/job/$jobId': typeof RepoRepoIdJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/jobs': typeof JobsRoute
  '/license': typeof LicenseRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/repos': typeof ReposRoute
  '/scans': typeof ScansRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pr/$repoId': typeof PrRepoIdRoute
  '/r/$token': typeof RTokenRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repo/$repoId/blockers': typeof RepoRepoIdBlockersRoute
  '/repo/$repoId/env': typeof RepoRepoIdEnvRoute
  '/repo/$repoId/fix': typeof RepoRepoIdFixRoute
  '/repo/$repoId/runs': typeof RepoRepoIdRunsRoute
  '/repo/$repoId/sandbox': typeof RepoRepoIdSandboxRoute
  '/repo/$repoId_/arch': typeof RepoRepoIdArchRoute
  '/repo/$repoId_/live-security': typeof RepoRepoIdLiveSecurityRoute
  '/repo/$repoId_/report': typeof RepoRepoIdReportRoute
  '/repo/$repoId/': typeof RepoRepoIdIndexRoute
  '/repo/$repoId/job/$jobId': typeof RepoRepoIdJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/jobs'
    | '/license'
    | '/privacy'
    | '/reports'
    | '/repos'
    | '/scans'
    | '/security'
    | '/settings'
    | '/terms'
    | '/blog/$slug'
    | '/pr/$repoId'
    | '/r/$token'
    | '/repo/$repoId'
    | '/repo/$repoId/blockers'
    | '/repo/$repoId/env'
    | '/repo/$repoId/fix'
    | '/repo/$repoId/runs'
    | '/repo/$repoId/sandbox'
    | '/repo/$repoId/arch'
    | '/repo/$repoId/live-security'
    | '/repo/$repoId/report'
    | '/repo/$repoId/'
    | '/repo/$repoId/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/jobs'
    | '/license'
    | '/privacy'
    | '/reports'
    | '/repos'
    | '/scans'
    | '/security'
    | '/settings'
    | '/terms'
    | '/blog/$slug'
    | '/pr/$repoId'
    | '/r/$token'
    | '/repo/$repoId/blockers'
    | '/repo/$repoId/env'
    | '/repo/$repoId/fix'
    | '/repo/$repoId/runs'
    | '/repo/$repoId/sandbox'
    | '/repo/$repoId/arch'
    | '/repo/$repoId/live-security'
    | '/repo/$repoId/report'
    | '/repo/$repoId'
    | '/repo/$repoId/job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/jobs'
    | '/license'
    | '/privacy'
    | '/reports'
    | '/repos'
    | '/scans'
    | '/security'
    | '/settings'
    | '/terms'
    | '/blog/$slug'
    | '/pr/$repoId'
    | '/r/$token'
    | '/repo/$repoId'
    | '/repo/$repoId/blockers'
    | '/repo/$repoId/env'
    | '/repo/$repoId/fix'
    | '/repo/$repoId/runs'
    | '/repo/$repoId/sandbox'
    | '/repo/$repoId_/arch'
    | '/repo/$repoId_/live-security'
    | '/repo/$repoId_/report'
    | '/repo/$repoId/'
    | '/repo/$repoId/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  JobsRoute: typeof JobsRoute
  LicenseRoute: typeof LicenseRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  ReposRoute: typeof ReposRoute
  ScansRoute: typeof ScansRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PrRepoIdRoute: typeof PrRepoIdRoute
  RTokenRoute: typeof RTokenRoute
  RepoRepoIdRoute: typeof RepoRepoIdRouteWithChildren
  RepoRepoIdArchRoute: typeof RepoRepoIdArchRoute
  RepoRepoIdLiveSecurityRoute: typeof RepoRepoIdLiveSecurityRoute
  RepoRepoIdReportRoute: typeof RepoRepoIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId': {
      id: '/repo/$repoId'
      path: '/repo/$repoId'
      fullPath: '/repo/$repoId'
      preLoaderRoute: typeof RepoRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/$repoId': {
      id: '/pr/$repoId'
      path: '/pr/$repoId'
      fullPath: '/pr/$repoId'
      preLoaderRoute: typeof PrRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId/': {
      id: '/repo/$repoId/'
      path: '/'
      fullPath: '/repo/$repoId/'
      preLoaderRoute: typeof RepoRepoIdIndexRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId_/report': {
      id: '/repo/$repoId_/report'
      path: '/repo/$repoId/report'
      fullPath: '/repo/$repoId/report'
      preLoaderRoute: typeof RepoRepoIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId_/live-security': {
      id: '/repo/$repoId_/live-security'
      path: '/repo/$repoId/live-security'
      fullPath: '/repo/$repoId/live-security'
      preLoaderRoute: typeof RepoRepoIdLiveSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId_/arch': {
      id: '/repo/$repoId_/arch'
      path: '/repo/$repoId/arch'
      fullPath: '/repo/$repoId/arch'
      preLoaderRoute: typeof RepoRepoIdArchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId/sandbox': {
      id: '/repo/$repoId/sandbox'
      path: '/sandbox'
      fullPath: '/repo/$repoId/sandbox'
      preLoaderRoute: typeof RepoRepoIdSandboxRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/runs': {
      id: '/repo/$repoId/runs'
      path: '/runs'
      fullPath: '/repo/$repoId/runs'
      preLoaderRoute: typeof RepoRepoIdRunsRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/fix': {
      id: '/repo/$repoId/fix'
      path: '/fix'
      fullPath: '/repo/$repoId/fix'
      preLoaderRoute: typeof RepoRepoIdFixRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/env': {
      id: '/repo/$repoId/env'
      path: '/env'
      fullPath: '/repo/$repoId/env'
      preLoaderRoute: typeof RepoRepoIdEnvRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/blockers': {
      id: '/repo/$repoId/blockers'
      path: '/blockers'
      fullPath: '/repo/$repoId/blockers'
      preLoaderRoute: typeof RepoRepoIdBlockersRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
    '/repo/$repoId/job/$jobId': {
      id: '/repo/$repoId/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/repo/$repoId/job/$jobId'
      preLoaderRoute: typeof RepoRepoIdJobJobIdRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
  }
}

interface RepoRepoIdRouteChildren {
  RepoRepoIdBlockersRoute: typeof RepoRepoIdBlockersRoute
  RepoRepoIdEnvRoute: typeof RepoRepoIdEnvRoute
  RepoRepoIdFixRoute: typeof RepoRepoIdFixRoute
  RepoRepoIdRunsRoute: typeof RepoRepoIdRunsRoute
  RepoRepoIdSandboxRoute: typeof RepoRepoIdSandboxRoute
  RepoRepoIdIndexRoute: typeof RepoRepoIdIndexRoute
  RepoRepoIdJobJobIdRoute: typeof RepoRepoIdJobJobIdRoute
}

const RepoRepoIdRouteChildren: RepoRepoIdRouteChildren = {
  RepoRepoIdBlockersRoute: RepoRepoIdBlockersRoute,
  RepoRepoIdEnvRoute: RepoRepoIdEnvRoute,
  RepoRepoIdFixRoute: RepoRepoIdFixRoute,
  RepoRepoIdRunsRoute: RepoRepoIdRunsRoute,
  RepoRepoIdSandboxRoute: RepoRepoIdSandboxRoute,
  RepoRepoIdIndexRoute: RepoRepoIdIndexRoute,
  RepoRepoIdJobJobIdRoute: RepoRepoIdJobJobIdRoute,
}

const RepoRepoIdRouteWithChildren = RepoRepoIdRoute._addFileChildren(
  RepoRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  JobsRoute: JobsRoute,
  LicenseRoute: LicenseRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  ReposRoute: ReposRoute,
  ScansRoute: ScansRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PrRepoIdRoute: PrRepoIdRoute,
  RTokenRoute: RTokenRoute,
  RepoRepoIdRoute: RepoRepoIdRouteWithChildren,
  RepoRepoIdArchRoute: RepoRepoIdArchRoute,
  RepoRepoIdLiveSecurityRoute: RepoRepoIdLiveSecurityRoute,
  RepoRepoIdReportRoute: RepoRepoIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
